### ISSUE TITLE
[RoCE bandwidth] should it be double when using bonding network ?

### ISSUE THREAD

**Issue by elevenxiang** [NVIDIA/nccl#1015]
Hi,

From the code below, I found it will only consider one port bandwidth for bonding network.
Our RoCE bonding network bandwidth can reach 180+ GB/s on each single NIC(mlx5_bond_x) when using ib_write_bw tool.

And we will use it to search and calculate graph channels, so can we really found the best graph channels ?

https://github.com/NVIDIA/nccl/blob/4365458757e4107ecbf629b2fd6e0e19a5d237c2/src/transport/net_ib.cc#L225C1-L225C1

          ncclIbDevs[ncclNIbDevs].speed = ncclIbSpeed(portAttr.active_speed) * ncclIbWidth(portAttr.active_width);

Thanks

**Comment by sjeaugey** [comment]
That's because if you use a single QP (the default), only one port will be used.

Can you try with `NCCL_IB_QPS_PER_CONNECTION=2 NCCL_IB_SPLIT_DATA_ON_QPS=0` ? The IB Verbs networking API does not allow us to select on which IB port a specific QP will be mapped. So we can't guarantee 100% that the two QPs will land on the two ports. But given they're created one after the other, it might work.

**Comment by elevenxiang** [comment]
> That's because if you use a single QP (the default), only one port will be used.
> 
> Can you try with `NCCL_IB_QPS_PER_CONNECTION=2 NCCL_IB_SPLIT_DATA_ON_QPS=0` ? The IB Verbs networking API does not allow us to select on which IB port a specific QP will be mapped. So we can't guarantee 100% that the two QPs will land on the two ports. But given they're created one after the other, it might work.

Yes, we found the BW will become higher after setting IB_QPS_PER_CONNECTION to more than 2 or 4.
And we have already confirmed with our network team, they suggested us to use more QP

If this, could we double the speed ?  it seemed that it will search out more channel numbers ? since we need more NVLink to meet the NIC bandwidth

Thanks

**Comment by sjeaugey** [comment]
Increasing the number of QPs in the network layer will allow to use more QPs without increasing the number of channels hence the number of SMs. NCCL will still use enough SMs to reach the peak bandwidth but it might have been doing it already.

What I'm not sure about is how the bonded port is seen in terms of bandwidth. NCCL might consider the bonded port as half its bandwidth, as IBV queries will return the speed of one NIC IIRC, and that may cause NCCL to not reach peak performance because it will tune the number of flows (ring/trees) for half the bandwidth.

**Comment by elevenxiang** [comment]
> Increasing the number of QPs in the network layer will allow to use more QPs without increasing the number of channels hence the number of SMs. NCCL will still use enough SMs to reach the peak bandwidth but it might have been doing it already.
> 
> What I'm not sure about is how the bonded port is seen in terms of bandwidth. NCCL might consider the bonded port as half its bandwidth, as IBV queries will return the speed of one NIC IIRC, and that may cause NCCL to not reach peak performance because it will tune the number of flows (ring/trees) for half the bandwidth.

Yes, this is exactly what I am concerned, our IBV query only returned the half bandwidth of the bonded NIC.
So I wonder if the NCCL could search out the best graph channels under NIC half bandwidth ?

Thanks

**Comment by sjeaugey** [comment]
I see. Indeed you'd need to dump the topology, double the link speed then reinject it. Quite bothersome, but last time I checked I could not find the information that the port was a bonded interface and therefore could not report the right speed nor automatically use 2 QPs.

**Comment by elevenxiang** [comment]
got it.
Thank you so much ~
