### ISSUE TITLE
ncclSend performance

### ISSUE THREAD

**Issue by heavyrain-lzy** [NVIDIA/nccl#1025]
I launch an `ncclSend` operator on the device 0, while the device 1 begin to receive it after a long time. During the time waiting for the device 1 to receive the buffer, the `ncclSend` kernel is running by the Nsight Sysytem tool. Why does the situation occur？Does the `ncclSend` have a bad impact on the performance during the time it hangs?

**Comment by sjeaugey** [comment]
I'm not sure what you mean by "the ncclSend kernel is running by the Nsight Sysytem tool". Do you mean you can see the ncclSend kernel running during the entire time in Nsight System until ncclRecv starts? That would be normal, as ncclSend needs to wait for ncclRecv before it can send its data, especially if the size is larger than the internal buffer size.
If you don't want ncclSend to spin for a long time, you can either delay its start to later on (you may synchronize ranks through CPU mechanisms) or post the ncclRecv earlier, e.g. using double buffering so that there is always a buffer to receive to.

**Comment by heavyrain-lzy** [comment]
I have another question that during the time when ncclSend kernel is runing but the ncclRecv have not be launched, does the ncclSend still consume the resources of GPU device? If I launch a kernel of calculation such as matrix multiply during the time, does the execution time of it will become longer?

**Comment by sjeaugey** [comment]
Possibly yes. If the kernel uses SMs and polls on the memory, it can cause lower performance for other workloads.

**Comment by heavyrain-lzy** [comment]
> Possibly yes. If the kernel uses SMs and polls on the memory, it can cause lower performance for other workloads.
