### ISSUE TITLE
NCCL performance comparison with MSCCL++

### ISSUE THREAD

**Issue by haswelliris** [NVIDIA/nccl#1088]
[mscclpp](https://github.com/microsoft/mscclpp#performance) is now officially released.   
According to their test data, mscclpp demonstrates exceptional efficiency, being twice as fast as nccl when dealing with small data sizes and exhibiting a 25% speed advantage in very large sizes.   
![mscclpp_vs_nccl_comparison_num_nodes_2](https://github.com/NVIDIA/nccl/assets/16082130/fdbd50b3-f7f8-46c3-b7c0-b257eff0b4f2)   
  
My point of discussion is this:   
I had anticipated NCCL to perform more efficiently with large data sizes, yet, surprisingly, their test outcomes came across as rather slower.

**Comment by sjeaugey** [comment]
NCCL doesn't only optimize for peak performance. We also optimize for SM usage. You could probably get similar performance with 2x the number of SMs but that could significantly impact the overlap with compute, which is why sometimes NCCL is tuned to make a compromise between performance and SM usage. On top of that, this difference is only possible on 2 nodes, and on that particular platform. On most other platforms, or on 3+ nodes, this difference would probably no longer exist.

**Comment by labfor** [comment]
According to experience from our team, this figure dose not reflect actual peak performance of nccl benchmarked on a100 servers.
