### ISSUE TITLE
Dual 4090 bandwidth slower with PCIe

### ISSUE THREAD

**Issue by YZP17121579** [NVIDIA/nccl#1309]
![4090topo](https://github.com/NVIDIA/nccl/assets/36131678/8cdb18e8-31f9-4777-94df-1d5ef38b0305)
<img width="1439" alt="nccl-03" src="https://github.com/NVIDIA/nccl/assets/36131678/d9224d54-aecb-44f6-9a81-cdb6b414fe89">
<img width="1428" alt="nccl-23" src="https://github.com/NVIDIA/nccl/assets/36131678/a30e367e-b909-4bb3-a34a-8431e805e60f">

As the graph above shows, the topo between GPU0 and GPU3 is SYS,  and PIX between GPU2 and GPU3. I'm wondering why the bandwidth between GPU2 and GPU3 is much slower than the other?

**Comment by sjeaugey** [comment]
That's because GeForce cards don't support GPU Direct P2P (direct PCI-to-PCI communication). Therefore, the traffic cannot stay local to the PCI switch and has to go back to the CPU, causing a 2x increase in load on the PCI link to the CPU compared to the case where the 2 GPUs are on different sockets.
