### ISSUE TITLE
Where is internal implementation of isend/irecv defined?

### ISSUE THREAD

**Issue by ZhiyiHu1999** [NVIDIA/nccl#1339]
Hello! If I do not use NCCL net plugin and only use internal implementation of isend/irecv, I wonder where and how the isend/irecv is defined here: https://github.com/NVIDIA/nccl/blob/5d3ab08b69754cb863ab1bf6e3fb6f7612bb725b/src/include/net.h#L32 and here: https://github.com/NVIDIA/nccl/blob/5d3ab08b69754cb863ab1bf6e3fb6f7612bb725b/src/net.cc#L38. 

Is it defined in nccl.h which I cannot find or somewhere else? Thanks a lot!

**Comment by kiskra-nvidia** [comment]
> Hello! If I do not use NCCL net plugin and only use internal implementation of isend/irecv, I wonder where and how the isend/irecv is defined

See, e.g.: https://github.com/NVIDIA/nccl/blob/178b6b759074597777ce13438efb0e0ba625e429/src/transport/net_socket.cc#L543 and https://github.com/NVIDIA/nccl/blob/178b6b759074597777ce13438efb0e0ba625e429/src/transport/net_ib.cc#L1590

> Is it defined in nccl.h which I cannot find or somewhere else? Thanks a lot!

`nccl.h` is automatically generated from https://github.com/NVIDIA/nccl/blob/master/src/nccl.h.in while building NCCL. You won't find isend/irecv in there though because those functions are not part of the public NCCL API.

**Comment by alokprasad** [comment]
@kiskra-nvidia nccl is not released as binary , so didnt understand your statement that "functions are not part of the public NCCL API."
