### ISSUE TITLE
Improve ReduceScatter

### ISSUE THREAD

**Issue by GeofferyGeng** [NVIDIA/nccl#1413]
ReduceScatter is becoming increasingly important, but its performance shows a noticeable decline as the cluster size increases. Do you have plans to support the NVLSTree algorithm for ReduceScatter to improve this situation?

**Comment by sjeaugey** [comment]
Yes we have plans to add a new algorithm to improve ReduceScatter/AllGather performance at scale. It cannot be the NVLSTree algorithm though, since the *Tree algorithms only apply to allreduce (they could also probably apply to broadcast / reduce, but not to reducescatter/allgather).

So we need to design a completely new algorithm and it's quite complex .. hence it takes time. The first version will only support inter-node communication (1 GPU per node); we'll work on adding intra-node after that (probably combining the algorithm with NVLS).

What is your use case? Do you use ReduceScatter with all GPUs or with only one GPU per node?

**Comment by GeofferyGeng** [comment]
Yes, you are right. Reducescatter is different from all-reduce, so we can't introduce tree algorithm  to NVLS and achieve improvement.

My case is not typical. We deliver environments to our customers; therefore, we test ReduceScatter with all GPUs.

In practical environments, ReduceScatter is most commonly used for data parallelism (DP), which is generally inter-node (since tensor parallelism (TP) involves a larger amount of data communication, making TP more suitable for intra-node). Therefore, I believe your idea of initially supporting inter-node communication (1 GPU per node) will be very practical.

Thank you very much for your attention and assistance. Your support is greatly appreciated!
