### ISSUE TITLE
[Question] NCCL kernels occupy the full SM?

### ISSUE THREAD

**Issue by chenhongyu2048** [NVIDIA/nccl#1424]
I have read an issue mentioned this `NCCL kernels occupy the full SM`. And I wonder about it. 
If I use a ncclsend kernel with <<<1, 640>>>, will it hold a SM (or SM process block) until it finish the transfer?
btw, another question is that can I use more than 1 SM for ncclsend by modifying `NCCL_MAX_NCHANNELS`? (In fact, I'm not quite sure what NCCL's default value is for `NCCL_MAX_NCHANNELS` when communicating with P2P or collective ops)

**Comment by kiskra-nvidia** [comment]
You may want to experiment with `NCCL_NCHANNELS_PER_NET_PEER`...

**Comment by chenhongyu2048** [comment]
Thanks for your advice! It will helps me a lot. 
But I still have a question, what is the difference between `NCCL_NCHANNELS_PER_NET_PEER` and `NCCL_MAX_NCHANNELS`? And which one should I use if I have several serial and lightweight send-recv?

**Comment by kiskra-nvidia** [comment]
`NCCL_NCHANNELS_PER_NET_PEER` is a per-peer setting used for send/recv type operations, whereas `NCCL_MAX_NCHANNELS` is  used primarily for collectives I think. `NCCL_NCHANNELS_PER_NET_PEER` is typically `2`, though I think with many peers NCCL could reduce it to `1`; setting it to `4` might give a performance benefit in some scenarios at the expense of more GPU resources being used by NCCL, but anything beyond that would probably be an overkill.

We try not to expose too many knobs to users as it causes confusion, which is why `NCCL_NCHANNELS_PER_NET_PEER` is not documented. NCCL tries to choose reasonable values by default; if you run with `NCCL_DEBUG=INFO`, NCCL will print the values it picks.

**Comment by chenhongyu2048** [comment]
Thanks! This really helps me.

**Comment by chenhongyu2048** [comment]
I'm sorry for that I still meet some problem. 
After I have set `NCCL_NCHANNELS_PER_NET_PEER` as `2` or `4`, I find that the ncclSend kernel is still of griddim<<<1,1,1>>> and blockdim<<<640,1,1>>> in nsys profile result.
I want to know if this is a right phenomenon?
