### ISSUE TITLE
Build failure on nccl 2.23.4. Missing shmutils.h

### ISSUE THREAD

**Issue by mhuguesaws** [NVIDIA/nccl#1448]
Building NCCL 2.23.4 lead to failure due to missing `shmutils.h`

```
0.894 include/proxy.h:16:10: fatal error: shmutils.h: No such file or directory
0.894    16 | #include "shmutils.h"
```

Looks like `shmutils.h` is missing.

**Comment by kiskra-nvidia** [comment]
Confirmed. Weird...

**Comment by kiskra-nvidia** [comment]
I added the missing header files. Thanks!

**Comment by mhuguesaws** [comment]
Thank you. Do you plan to update the tag with the latest changes or create a new release?

**Comment by kiskra-nvidia** [comment]
I just updated the tag.

**Comment by sjeaugey** [comment]
Sorry, my mistake, I failed to `git add` the two new files in `src/include`. I pushed a new commit with the two files then merged with current master. I also move the tag to that new full commit. Thanks @kiskra-nvidia for the quick fix!

**Comment by bdice** [comment]
Hi @kiskra-nvidia, thanks for the fix. In the future, could you consider making a new tag for the bugfix? Moving tags can cause problems because git tags are often treated as immutable by repository consumers. We had to fix this in the conda-forge nccl release here: https://github.com/conda-forge/nccl-feedstock/pull/113#discussion_r1779181730

If a new tag had been created instead, the release would have been deployed automatically and saved time / manual intervention. Thanks for your consideration!

**Comment by sjeaugey** [comment]
Thanks @bdice for the feedback. Moving the tag is cleaner for the long term history, but indeed can confuse repo consumers.

Problem is, I'm not sure how we could have created a new tag. We could not name the tag differently. When people look for the source code of NCCL 2.23.4 (i.e. the binary we release at developer.nvidia.com/nccl), they need to be able to easily find the tag corresponding to 2.23.4. So we have to call it that way and make it point to the correct commit.

I think the only thing we can do is try to make sure we don't push a broken commit. What do you think?
