### ISSUE TITLE
Some question about NCCL_IB_SCA

### ISSUE THREAD

**Issue by shanleo2024** [NVIDIA/nccl#1478]
Hi dear developer,

Does the NCCL_IB_SCA environment variable only affect the RDMA process?
I found that there are also changes when initializing channel search.

I have 4 NODEs, 4 GPU cards and 4 IB HCAs for each NODE.
I run nccl_test like:
`mpirun -np 16 -H 172.16.4.36:4,172.16.4.38:4,172.16.4.39:4,172.16.4.40:4`
and have a script to set the **NCCL_IB_SCA** for each rank:

```
#!/bin/bash

ulimit -n 100000
APP="${@}"

let local_rank=$OMPI_COMM_WORLD_LOCAL_RANK%4
echo $OMPI_COMM_WORLD_LOCAL_RANK
echo ${local_rank}
case ${local_rank} in
[0])
  #export UCX_NET_DEVICES="mlx5_0:1"
  export NCCL_IB_HCA=mlx5_0:1
  numactl --cpunodebind=0 --membind=0 \
  $APP
  ;;
[1])
  #export UCX_NET_DEVICES="mlx5_1:1"
  export NCCL_IB_HCA=mlx5_1:1
  numactl --cpunodebind=1 --membind=1 \
  $APP
  ;;
[2])
  #export UCX_NET_DEVICES="mlx5_2:1"
  export NCCL_IB_HCA=mlx5_2:1
  numactl --cpunodebind=2 --membind=2 \
  $APP
  ;;
[3])
  #export UCX_NET_DEVICES="mlx5_3:1"
  export NCCL_IB_HCA=mlx5_3:1
  numactl --cpunodebind=3 --membind=3 \
  $APP
  ;;
esac
```

Does this valid to use NCCL_IB_HCA?
As there are some errors in ncclBuildRings:
![Image](https://github.com/user-attachments/assets/5a203cbc-8fb1-41d8-afb7-53617c5dbe4a)

Can you help me to trouble shooting this? thank you!

**Comment by sjeaugey** [comment]
This is expected. You should not set NCCL_IB_HCA differently on each rank. NCCL needs every rank to see every NIC so that each rank can find a global solution for collectives which optimizes all flows. If each rank sees a different node topology they'll end up with inconsistent solutions and fail connecting rings.

So just don't set NCCL_IB_HCA, NCCL is detecting the topology and is perfectly capable of knowing which NIC to use with which GPU. NCCL_IB_HCA is here only to disable some NICs in non-obvious cases where some NICs are functional but we don't want NCCL to use them at all (e.g. they're used for other purposes, or we want to see what performance we'd get with less NICs, etc).

**Comment by shanleo2024** [comment]
Thank you @sjeaugey , I am clear.
