### ISSUE TITLE
nccl kernel occupancy level

### ISSUE THREAD

**Issue by thyeros** [NVIDIA/nccl#181]
I checked a few nccl kernels, and found they all have pretty high registers/thread numbers, making occupancy level below 15% for all the checked cases. I saw also that makefile has -maxregcount 96 but looks it is overridden during the compile time. 

I wonder if this is a particular design choice specific to nccl  (based on some experiments?) or something to optimize in the future to improve the occupancy level for higher performance.

**Comment by thyeros** [comment]
I found launch_bound set as 256 threads/block. Any performance-related explanation would be helpful.

**Comment by sjeaugey** [comment]
NCCL is currently optimized to use as little SMs as possible, but not to share SMs with other kernels (which would probably not work well anyway). Each thread uses a lot of registers due to heavy unrolling, which is probably why you see a low occupancy.

The launch_bounds directive disappeared in 2.5, so maxrregcount=96 remains and is needed to make sure we can launch up to 640 threads while having enough registers (it would need to be lower if we wanted to launch 1024 threads).
