### ISSUE TITLE
Questions about the code of NCCL init—why does NCCL create an allgather ring instead of using mpi allgather 

### ISSUE THREAD

**Issue by NanYan1119** [NVIDIA/nccl#251]
I notice that in function initTransportsRank, need three times allgather to collective the info of all ranks. What is the reason? I think it is more convenient to use mpi allgather

**Comment by keisukefukuda** [comment]
NCCL does not depend on MPI.

I guess many people use MPI to Bcast the ncclUniqueId, but actually NCCL and MPI are different library and they are independent.

**Comment by sjeaugey** [comment]
That's a good question, and a good answer. We do not want to depend on MPI because you would then need to launch with MPI (and it would bring a very large library for a small functionality).

That said, the bootstrap allgather is not very fast so we avoid doing too many, which is why we merged them into 3 calls. We hope to reduce that to 2 in the next version.

The first allgather call is needed to build a table of whose rank is on which node, GPU, ...The next allgather operations are needed because the ring creation system is distributed, so each rank computes part of the final solution, which we then exchange with all so that each rank has a complete view of the rings.

**Comment by sjeaugey** [comment]
Closing as I believe the question has been answered.
