### ISSUE TITLE
What algorithm is ncclAllReduce using?

### ISSUE THREAD

**Issue by chrishkchris** [NVIDIA/nccl#256]
To all-reduce the parameter, we can use three different program flows:
(i) ncclAllReduce
(ii) ncclReduceScatter + ncclAllGather
(iii) ncclReduce + ncclBroadcast

My two questions are:
(1) Is (i) equivalent to (ii)? If not, what exactly all-reduce algorithm (i) is using?
(2) Does (iii) perform like GPU parameter server?

Thank you very much!

**Comment by keisukefukuda** [comment]
As far as I understand (and please correct me if i'm wrong)

(1) No. Theare are two reasons.
First, ncclAllReduce internally switch algorithms between (ii) and (iii), depending on the buffer size. 
Second, even when ncclAllReduce uses "reduce-scatter-plus-allgather" algorithm, it is different from calling ncclReduceScatter() and then ncclAllGather() in the implementation level. Algorithms in NCCL are implemented using pipelining techniques and it is faster to fuse the two algorithms into a single pipeline. It is a large overhead if there is a barrier and pipeline flush between the two.

(2) It is slightly different from parameter server.  The algorithms are implemented in a tree-like fasion, so there are root, leaves, and branches. If the tree hight is just one, it's pretty much like parameter server style.

**Comment by sjeaugey** [comment]
Adding more details (though @keisukefukuda did a good summary).

(1) (i) is _functionally_ equivalent to (ii) and (iii). But the current implementation is not doing either of those.

The _Ring_ algorithm in NCCL is indeed equivalent to ReduceScatter+AllGather (with better pipelining), but those also come with constraints on the data layout of the intermediate step (how data lands in output buffers) that we don't have in AllReduce. That lets us choose any layout we want to distribute the data. That's why alignment of sizes in ReduceScatter/AllGather is very important to keep good performance contrary to AllReduce.

The _Tree_ algorithm in NCCL is performing a Reduce+Broadcast per channel, but if you consider all the channels (up to 16 depending on your hardware configuration), it is performing multiple Reduce operations to up to 16 different roots (which is a kind of ReduceScatterV) then multiple Broadcasts from up to 16 roots (which is a kind of AllGatherV).

(2) Parameter servers are usually implemented as all-to-all rather than trees, and the point of parameter servers is to decouple the roots (CPU nodes) from the leaves (GPU nodes), to use more network ports and accelerate communication up to 2x. This can be a good idea if your GPU nodes are limited in terms of network bandwidth but you have a lot of unused (or cheap) CPU nodes that can match the total network bandwidth of you GPU nodes. This is explained at length on the BytePS page ([here](https://github.com/bytedance/byteps/blob/master/docs/rationale.md#cpu-only-ps-small-costs-huge-gains) or [here](https://github.com/bytedance/byteps/blob/master/docs/faq.md#since-the-bottleneck-is-the-nic-of-gpu-machines-why-not-add-more-nics)), although one should keep in mind the 2x improvement with PS ([2x 20Gbps](https://github.com/bytedance/byteps/blob/master/README.md#performance)) is usually still orders of magnitude slower than the bandwidth of a NIC-heavy system like DGX1 (400 Gbps) or DGX2 (800Gbps).

**Comment by chrishkchris** [comment]
@keisukefukuda and @sjeaugey

Thank you very much for your reply! I have increased lots of my understanding concerning the implementation in NCCL after reading both your replies.

I have two more questions:

1. After reading both your replies, today I read the NCCL documentation again and know that the choice between the _Tree_ and _Ring_ algorithms depends on the environment variable NCCL_TREE_THRESHOLD (if I understand correctly).
I have another question: Does the choice of all-reduce algorithm depends also on the hardware topology: (i) depends on with/without NVLink, (ii) depends on intra-node/inter-node ?

2. Is Hierarchical All-reduce already implemented in ncclAllReduce? Hierarchical All-reduce consists of three steps:
(i) Intra-node Reduce
(ii) Inter-node All-Reduce
(iii) Intra-node Broadcast
If this is not already implemented in NCCL: If I need Hierarchical All-reduce in my application, is it a good way to use two NCCL communicators separately for providing the inter-node and intra-node communications respectively? (maybe sharing the same cuda stream)

Thank you so much!

**Comment by sjeaugey** [comment]
1. The tree threshold is computed using a complex formula which does depend on a lot of factors including the number of nodes, whether we use NVLink or not, ... see https://github.com/NVIDIA/nccl/blob/master/src/init.cc#L354-L377

2. I'm not sure why you would need a hierarchical allreduce in your application. Wouldn't you just want to have the fastest implementation ?
Anyway, if you want to implement it yourself that way, sure you can decompose in multiple operations on the same stream. It might be slower than using a single allreduce though.

**Comment by chrishkchris** [comment]
@sjeaugey

Thank you so much for your reply and the information of the code. 

1. From the source code (ncclTreeThreshold) now I understand more how it switches between ring and tree algorithms. It is looking like the code uses the tradeoff between both the latency and bandwidth performance of the ring and tree algorithms to determine which one is using.

2. For a small number of nodes / GPUs I am sure that without Hierarchical All-reduce is better. The reason I plan to use Hierarchical All-reduce in my application is to target for a greater throughput in a large scale data parallel deep learning (Resnet-50) test case using 128 GPUs (i.e. 16 nodes of AWS K80 p2.x8large or V100 p3.x16large). 
I am not sure it could be useful if I use Hierarchical All-reduce to utilize the intra-node bandwidth (otherwise theoretically seems like intra-node communication is bottlenecked by the inter-node network bandwidth if they are in the same large ring).


Thank you very much again for your reply. Now I think I have enough understanding in NCCL to use it in my application.

**Comment by jyhuang91** [comment]
@sjeaugey 

Can you explain a bit what is the channel concept in NCCL.
I also wondered how close the Tree algorithm match to the double binary tree, if the Tree has coloring on the edges of the tree for scheduling?

Thanks

**Comment by sjeaugey** [comment]
Channels are independent, parallel data flows. For example, we create different channels to be able to aggregate the bandwidth of multiple NICs. In practice, for each flow we find during the topology search, we create 2 channels later on. Each channel runs on a different CUDA block, i.e. SM. Having 2 channels per flow has two goals : make sure we cover bubbles from one with the other, and permit double binary trees. Indeed, with double binary trees, for each NIC, we need to split the data onto two trees running at half speed each.

So on a node with NVLink and 4 NICs, the topology search we would find 4 paths within the node running at 12 GB/s, which will result in 8 channels (2 per NIC) each supposed to process data at 6 GB/s.

**Comment by szhengac** [comment]
Hi @sjeaugey. Does it mean that the maximum number of channels we can use is 2 if there is only 1 NIC on the node? Or we can still use more channels and have multiple double binary trees?

Another question: when we use Tree allreduce, does the GPU have idle time? For example, consider the Figure 2 in https://developer.nvidia.com/blog/massively-scale-deep-learning-training-nccl-2-4/. When the data has flowed to rank 16 and 15 in two binary trees, respectively, does rank 2 sit idle and wait for the broadcast?

Thanks!

**Comment by kwen2501** [comment]
The default number of channels would be 2 if there is only 1 NIC. You may use `NCCL_MIN_NCHANNELS` to set higher number of channels, but in most cases it would not bring speedup and will cost more SM resources. 

Yes, rank 2 would wait for the **initial** chunk of data to return from the top of the tree. However, when there are more than one chunk, the next chunk would immediately follow and not suffer from additional latency (pipeline effect).

**Comment by szhengac** [comment]
@kwen2501 Thanks for responding. We have chunks because we split the data in a single tree for pipelining or because we have multiple channels?

**Comment by kwen2501** [comment]
Because we split the data in a single tree for pipelining.

In fact, the initial latency in Tree is already much better than Ring, because of the less number of hops, O(log n) vs O(n).

**Comment by szhengac** [comment]
But Tree at the worst can have O(log n) times higher communication time than Ring? I think at least there is additional communication cost of O(C * log n) for the first and last chunks, where C is the chunk size.

**Comment by kwen2501** [comment]
No, what I mean is that Tree has O(log n) hops while Ring has O(n) hops, hence Tree can have a latency advantage at large scale.

**Comment by pzheng16** [comment]
Hi, thanks for your explanations of the algorithms. I am wondering what is the difference between double binary tree algorithms and ring algorithms (since they both split data into chunks for pipelining and have full bandwidth) in terms of bandwidth. And the binary tree algorithms have a latency advantage at large scale.
