### ISSUE TITLE
NCCL can use only one socket for communicating, even if configure more than one network interfaces for NCCL_SOCKET_IFNAME

### ISSUE THREAD

**Issue by yaohuaxin** [NVIDIA/nccl#278]
Version: NCCL version 2.5.6+cuda10.1
I have two machines, and each has two network interfaces and four GPUs. I configured the variable: 
NCCL_SOCKET_IFNAME=enP1p1s0f0,enP1p1s0f1
NCCL_DEBUG=INFO
NCCL_SOCKET_NTHREADS=2
NCCL_NSOCKS_PERTHREAD=2

But from the log, NCCL use only one interface, always "NET/Socket/0". And the bandwidth did improved compared with using only one network interface. Here is the log:
sh-01:98911:98911 [0] NCCL INFO Bootstrap : Using [0]enP1p1s0f0:10.30.0.127<0> [1]enP1p1s0f1:10.30.0.227<0>
sh-01:98911:98911 [0] NCCL INFO NET/Socket : Using [0]enP1p1s0f0:10.30.0.127<0> [1]enP1p1s0f1:10.30.0.227<0>
sh-03:97552:97552 [0] NCCL INFO Bootstrap : Using [0]enP1p1s0f0:10.30.0.129<0> [1]enP1p1s0f1:10.30.0.229<0>
sh-03:97552:97552 [0] NCCL INFO NET/Socket : Using [0]enP1p1s0f0:10.30.0.129<0> [1]enP1p1s0f1:10.30.0.229<0>

sh-01:98911:98923 [3] NCCL INFO Ring 00 : 3[b01000] -> 4[201000] [send] via NET/Socket/0
sh-03:97552:97571 [3] NCCL INFO Ring 00 : 7[b01000] -> 0[201000] [send] via NET/Socket/0

sh-03:97552:97570 [2] NCCL INFO Ring 01 : 0[201000] -> 6[a01000] [receive] via NET/Socket/0
sh-03:97552:97567 [0] NCCL INFO Ring 01 : 3[b01000] -> 4[201000] [receive] via NET/Socket/0

**Comment by sjeaugey** [comment]
Thanks for the report. I guess the graph search considers each NIC running at 100Gb/s hence believes using one NIC is enough to saturate the PCI bandwidth so there is no need to use two. This is a limitation of 2.5 since it doesn't detect the speed of the NICs.

Would you be able to recompile NCCL, changing the line below (set NET_WIDTH to the speed of your NICs, in GB/s) and see if it solves the issue ?
https://github.com/NVIDIA/nccl/blob/master/src/graph/topo.h#L20

2.6 should hopefully detect the speeds automatically and fix the issue. We'll keep you posted when we post a preview branch.

**Comment by sjeaugey** [comment]
NCCL 2.6 has been released now and should solve this problem. Please re-open if it is not the case.
