### ISSUE TITLE
Local installation are not taken into account by Slurm

### ISSUE THREAD

**Issue by netw0rkf10w** [NVIDIA/nccl#280]
Hello,

I have encountered some strange issue today when trying to install NCCL locally without root permission on a RedHat 7 server.

I downloaded the installer `nccl-repo-rhel7-2.5.6-ga-cuda10.1-1-1.x86_64.rpm` from NVIDIA's website and extracted it (as well as some sub-rpm files inside it) to finally obtain a `usr` folder with the following structure:

```
usr/
├── include
│   └── nccl.h
├── lib64
│   ├── libnccl.so -> libnccl.so.2
│   ├── libnccl.so.2 -> libnccl.so.2.5.6
│   ├── libnccl.so.2.5.6
│   └── libnccl_static.a
└── share
    └── doc
        ├── libnccl-2.5.6
        │   └── LICENSE.txt
        ├── libnccl-devel-2.5.6
        │   └── LICENSE.txt
        └── libnccl-static-2.5.6
            └── LICENSE.txt
```

I copied the content of the `usr` folder to `$HOME/local` (using this command: `rsync -a usr/ $HOME/local/`), then in my Slurm script I set:

```bash
export PATH=$HOME/local/bin:$PATH
export LD_LIBRARY_PATH=$HOME/local/lib64:$LD_LIBRARY_PATH
export CPATH=$HOME/local/include:$CPATH
export NCCL_DEBUG=VERSION
```

What I obtained in my logs was:

`NCCL version 2.4.8+cuda10.1`

which is the existing installation on the server and not the new 2.5.6 version that I have installed.

It seems that I missed some important steps during the installation. Maybe one cannot install the library locally in that usual way?

Thank you very much in advance for your help!

**Comment by sjeaugey** [comment]
I would advise to use the "agnostic" package (txz) to install in a user directory instead of extracting an RPM.

Other than that, it should work (we're doing it all the time).

Can you run `ldd` on the binary to check which library it is using on the head node ? That should sort all mistakes in *PATH. Also it would double check that NCCL is linked dynamically (if NCCL is linked statically, you'll need to relink your binary with the new NCCL version).

If it is correct, then you can run it again through SLURM (`srun <srun options> ldd <binary>`). It could be that the compute node cannot access your new NCCL directory.

**Comment by netw0rkf10w** [comment]
@sjeaugey Thank you for your reply. I will try again with the "agnostic" package (I should have noticed this one earlier).

**Comment by sjeaugey** [comment]
Closing old issue. Please re-open if needed.
