### ISSUE TITLE
What is LL128 Protocol?

### ISSUE THREAD

**Issue by zarzen** [NVIDIA/nccl#281]
Hi,
Could you please explain the `LL128 Protocol`? 
The only thing I know from dev-doc is that we can specify "NCCL_PROTO"  with three values "LL,LL128,Simple". But it is not clear the differences between these three settings or their combinations. Could you refer to some material for a detailed explanation? Thanks!

**Comment by sjeaugey** [comment]
LL128 is working similarly to LL : the flag comes along with the data (so that we avoid expensive memory barriers and get better latency), considering stores as an atomic operation : when we see the flag, the data is valid.

The difference is that LL relies on 8 Bytes stores being atomic (with 4B data / 4 B flag) while LL128 relies on 128B stores being seen in order (with 120B data / 8 B flag). Which makes LL maximum bandwidth 50% of the peak (because 50% of the payload is the flag), while LL128 can achieve 95% peak.

But whether LL128 is functional and fast actually depends on many factors like the way we communicate between GPUs (PCI or NVLink) and where the buffers reside (GPU memory or system memory). If a 128B store gets split and reordered (or is read in a reverse order), you risk silent data corruption so I would not advise forcing it. NCCL should automatically enable it when it is safe to use.

`NCCL_PROTO` is there mostly for debugging and workarounds in the case there is a bug with a given protocol, so that users can set e.g. `NCCL_PROTO=^LL128` to disable it.

**Comment by zarzen** [comment]
Really thanks for your quick response! 
So LL, LL128, Simple are protocols used for exchanging data for collective operations among different ranks? Is there any document for the meanings of each flag? Thanks!

**Comment by cliffwoolley** [comment]
Yes, the protocols are for data exchange within a given collective.  The `LL` protocols are the "low latency" ones.  All of these algorithms are heavily pipelined so that we can try to keep all links in the system busy concurrently all the time; the flags are just used to signal that the tail end of a given slice of data has been delivered and is ready to be consumed for the next stage of the pipeline.

**Comment by zarzen** [comment]
What are the links in the system here? @cliffwoolley

**Comment by sjeaugey** [comment]
Pretty much everything we need to achieve the maximum performance : NVLink, PCI, and network cards (when communicating between different systems).

**Comment by zarzen** [comment]
@sjeaugey Thanks!
Will NCCL use NVLink, PCI and network cards simultaneously? e.g. when both PCI and NVLink are available to 4 GPUs on a server, if we do ring allreduce with `ring-number > 1` will NCCL pass data in both PCI and NVLink?

**Comment by sjeaugey** [comment]
NCCL will not use both PCI and NVLink to communicate between a Pair or GPUs. It wouldn't make much sense since NVLink speed is much higher than NVLink, plus CUDA doesn't let us do so. So it will only use PCI between GPUs of the same machine if it cannot use NVLink between them.

But when communicating inter-node, it will combine NVLink (intra-node) with PCI and network (inter-node).

**Comment by zarzen** [comment]
Sorry, I am confused about the last part, `combine NVLink (intra-node) with PCI`. 
Assume two machines equipped with 4 GPUs each, and GPUs are connected through NVLink, but NIC is not support GPUDirect RDMA. If we do ring all reduce over 8 GPUs, then how does NCCL combine NVLink with PCI here? 
Do you mean the NCCL will transfer data to peers in single machine with both PCI and NVLink to maximize bandwidth? (or maybe, NCCL is going to split ring all reduce into two parts, 1) all reduce on local 4 GPUs, 2) copy the allreduced results through PCI to Host memory for NIC to do inter-node all reduce?)

**Comment by sjeaugey** [comment]
In the NVLink case, PCI and network go together. We'll use NVLink for intra-node (only, if possible) and PCI/NICs for inter-node.

The NIC<->GPU traffic will use PCI links. NCCL will detect where NICs are attached and whether using more NICs will result in better performance.

**Comment by zarzen** [comment]
Thanks! that is much clear.

**Comment by pro-panda** [comment]
What benefits does LL have over Simple for small transfers? How does adding a flag help?

**Comment by kwen2501** [comment]
LL achieves lower latency than Simple for small messages by sending the flag along with the data. When we see the flag, the data is valid, so that we can avoid expensive memory barriers.

**Comment by pro-panda** [comment]
@kwen2501 what do you mean by memory barriers?

**Comment by cliffwoolley** [comment]
@pro-panda - See https://en.m.wikipedia.org/wiki/Memory_barrier .

**Comment by Eiji911** [comment]
> LL128 is working similarly to LL : the flag comes along with the data (so that we avoid expensive memory barriers and get better latency), considering stores as an atomic operation : when we see the flag, the data is valid.
> 
> The difference is that LL relies on 8 Bytes stores being atomic (with 4B data / 4 B flag) while LL128 relies on 128B stores being seen in order (with 120B data / 8 B flag). Which makes LL maximum bandwidth 50% of the peak (because 50% of the payload is the flag), while LL128 can achieve 95% peak.
> 
> But whether LL128 is functional and fast actually depends on many factors like the way we communicate between GPUs (PCI or NVLink) and where the buffers reside (GPU memory or system memory). If a 128B store gets split and reordered (or is read in a reverse order), you risk silent data corruption so I would not advise forcing it. NCCL should automatically enable it when it is safe to use.
> 
> `NCCL_PROTO` is there mostly for debugging and workarounds in the case there is a bug with a given protocol, so that users can set e.g. `NCCL_PROTO=^LL128` to disable it.

LL will 

> “which makes LL maximum bandwidth 50% of the peak" does it mean the data size transported  inter nodes will double？or just effect intra-node？

**Comment by AddyLaddy** [comment]
LL means that for every 32-bits of payload we also send a 32-bit flag. So, we will double the amount of data sent or achieve 50% effective BW whichever way you want to look at it. But we only use LL for the very small message sizes, where latency, not network BW dominates.

The LL protocol is used both intra and inter node communications.

**Comment by MARD1NO** [comment]
> LL means that for every 32-bits of payload we also send a 32-bit flag. So, we will double the amount of data sent or achieve 50% effective BW whichever way you want to look at it. But we only use LL for the very small message sizes, where latency, not network BW dominates.
> 
> The LL protocol is used both intra and inter node communications.

Hi I just want to know how nccl use LL to do inter node communication ? Can you point the related code ? thanks

**Comment by alokprasad** [comment]
what about LL128 is it only for NVLINK or internode communication too?

**Comment by alokprasad** [comment]
@AddyLaddy do have slim sample program how to use Simple , or LL128 for data transfer?

**Comment by AddyLaddy** [comment]
NCCL automatically choose the PROTO based on number factors including the buffer size. Running the nccl-tests and setting `NCCL_DEBUG=INFO` `NCCL_DEBUG_SUBSYS=TUNING` will show you when LL128 is being utilized.

**Comment by renwuli** [comment]
@AddyLaddy do we choose LL128 for the reason that the size of L2 cache is 128B?

**Comment by MARD1NO** [comment]
> [@AddyLaddy](https://github.com/AddyLaddy) do we choose LL128 for the reason that the size of L2 cache is 128B?

LL128 Protocol is hardware details of GPU

**Comment by renwuli** [comment]
> > [@AddyLaddy](https://github.com/AddyLaddy) do we choose LL128 for the reason that the size of L2 cache is 128B?
> 
> LL128 Protocol is hardware details of GPU

Could you please explain it with more details? Thanks!

**Comment by MARD1NO** [comment]
> > > [@AddyLaddy](https://github.com/AddyLaddy) do we choose LL128 for the reason that the size of L2 cache is 128B?
> > 
> > 
> > LL128 Protocol is hardware details of GPU
> 
> Could you please explain it with more details? Thanks!

Here is author's explanation https://github.com/NVIDIA/nccl/issues/281#issuecomment-571816990. you can also check my zhihu blog: https://zhuanlan.zhihu.com/p/699178659
