### ISSUE TITLE
How does NCCL  work with  GPUs across NICs

### ISSUE THREAD

**Issue by paulkrishna** [NVIDIA/nccl#284]
Hi,
We  are experimenting with 2 GPus connected with two nodes/servers  with Mellanox NIC connecting both.   Does NCCL work in this configuration.  What SW/Config needs to be enabled to make NCCL view both GPU? We want to run NCCL testbench  in this configuration.  Has anyone done this before?

**Comment by sjeaugey** [comment]
I would say yes, this is pretty much what NCCL is all about : communicate between GPUs on the same machine and between machines through NICs, including Mellanox NICs.

I would advise to install NCCL and MPI on both nodes, then compile the NCCL tests with MPI support (see https://github.com/NVIDIA/nccl-tests#build) then run the tests on all the GPUs.

For example on two systems with 2 GPUs each :
```
mpirun -H host1:2,host2:2 ./build/all_reduce_perf -b 8 -e 1G -f 2
```

**Comment by paulkrishna** [comment]
Hi,  Thank you.    Few more queries.   How does NCCL  understands that  there are GPU s on other side of NIC, which NIC interface to talk to?  Is there a config file or env variable to set up?  BTW, our setup at this point is  Mellanox NIC ( ConnectX 6) and  Infiband interface. So you advice to  run EThnert on  this for whole thing to work?   Appreciate   advice.

**Comment by sjeaugey** [comment]
NCCL does not discover GPUs. It is only a communication library, not a parallel launcher. It only works on the GPUs that the user launches on. 

That's why applications need their own system to launch and manage processes on multiple machines, for example MPI (which is what we use in the NCCL tests). Then when the application is launched, the user passes the information of how many GPUs, which nodes, ... to the mpirun command (in my example above `-H host1:2,host2:2`).

Each framework using NCCL has its own way to launch on multiple GPUs. Some systems, like Horovod, use MPI. Some others have their own process management system.

**Comment by sjeaugey** [comment]
Closing as I think the question has been answered. Feel free to re-open if it wasn't the case.
