### ISSUE TITLE
Why choose 4MB DEFAULT_BUFFER_SIZE?

### ISSUE THREAD

**Issue by SmileOfKana** [NVIDIA/nccl#285]
In comm.h the DEFAULT_BUFFER_SIZE_BYTES is defined as 4MB. What is the rationale behind this value? Should I modify this value in order to optimize the communication performance?

**Comment by sjeaugey** [comment]
This value should be the best for performance in general.

That size is a delicate balance between memory usage/footprint and overhead. Since this buffer will be used as a circular FIFO, the size might need to fit in some TLB or data caches (GPU, NIC, CPU on some architecture if going through system memory), so it cannot be too large. On the other hand we want each step to be large enough (1/8 = 512K for trees, 1/4 = 1MB for rings) so that the protocol overhead is not too important with respect to the bandwidth.

While I would advise not to change this value because most of the time it would impact performance negatively, let us know if you see a different value making a significant performance improvement.

**Comment by SmileOfKana** [comment]
I use RDMA NICs for the network. Since RDMA supports up to 2GB message size, initially I wonder whether applying a larger message would give us some performance gain. I tried to double theis parameter and the effect is negligible. I guess this isn't a bottleneck of the system. Thanks for your explanation!

**Comment by SmileOfKana** [comment]
> This value should be the best for performance in general.
> 
> That size is a delicate balance between memory usage/footprint and overhead. Since this buffer will be used as a circular FIFO, the size might need to fit in some TLB or data caches (GPU, NIC, CPU on some architecture if going through system memory), so it cannot be too large. On the other hand we want each step to be large enough (1/8 = 512K for trees, 1/4 = 1MB for rings) so that the protocol overhead is not too important with respect to the bandwidth.
> 
> While I would advise not to change this value because most of the time it would impact performance negatively, let us know if you see a different value making a significant performance improvement.

I use RDMA NICs for the network. Since RDMA supports up to 2GB message size, initially I wonder whether applying a larger message would give us some performance gain. I tried to double theis parameter and the effect is negligible. I guess this isn't a bottleneck of the system. Thanks for your explanation!

**Comment by sjeaugey** [comment]
Closing.
