### ISSUE TITLE
Infiniband performance question

### ISSUE THREAD

**Issue by christopherhesse** [NVIDIA/nccl#319]
Hi!  Thanks for quickly responding to my previous issue about 2 node infiniband performance: https://github.com/NVIDIA/nccl/issues/307

We fixed that issue with our cluster (the cables were correct but there was a misconfiguration).  However, I wanted to know if the performance we are seeing is what we should expect:

If I run an 8-node job connected to a single switch:

ring (43.53): [nccl-singlerack-RING.txt](https://github.com/NVIDIA/nccl/files/4459496/nccl-singlerack-RING.txt)
tree (24.58): [nccl-singlerack-TREE.txt](https://github.com/NVIDIA/nccl/files/4459497/nccl-singlerack-TREE.txt)

And here's an 8-node job connected to two different switches:

ring (19.53): [nccl-doublerack-RING.txt](https://github.com/NVIDIA/nccl/files/4459494/nccl-doublerack-RING.txt)
tree (18.55): [nccl-doublerack-TREE.txt](https://github.com/NVIDIA/nccl/files/4459495/nccl-doublerack-TREE.txt)

It looks like the fix for #307 improves this particular issue, but the TREE performance seems to drop a little faster than I expected:

ring (43.57): [nccl-singlerack-master-RING.txt](https://github.com/NVIDIA/nccl/files/4459523/nccl-singlerack-master-RING.txt)
tree (36.84): [nccl-singlerack-master-TREE.txt](https://github.com/NVIDIA/nccl/files/4459525/nccl-singlerack-master-TREE.txt)

ring (39.93): [nccl-doublerack-master-RING.txt](https://github.com/NVIDIA/nccl/files/4459568/nccl-doublerack-master-RING.txt)
tree (32.40): [nccl-doublerack-master-TREE.txt](https://github.com/NVIDIA/nccl/files/4459569/nccl-doublerack-master-TREE.txt)

With 2 nodes I was getting an algbw > 50 GB/s for TREE mode.  Should I expect it to be down to 32 GB/s at 8 nodes?

Thanks!

**Comment by sjeaugey** [comment]
Tree is special for 2 nodes, it can achieve up to 2x the network bandwidth (because there is an imbalance, using less inter-node transfers, and more intra-node).

On more than 2 nodes, rings and trees should in theory be able to reach the same peak. In practice, we see that trees only achieve ~45 GB/s vs ~48 GB/s with rings. Also, the advantage of trees in terms of latency is also their weakness : the log2(n) steps to the root and back is causing some dead round-trip time which can only be covered with very large sizes, while rings use all links perfectly as soon as they have enough data to fill the ring.

Note that NCCL should tune things correctly and switch automatically from Tree to Ring when ring become better, so that should not be something you have to worry much about.

One thing to keep in mind though is that trees are more sensitive to IB static routing, especially as you scale. Because the tree communication pattern is more complex, it involves more cross communication, and there is a higher chance three flows end up on the same link somewhere in the fabric. Since each flow carries half of the data, you end up with trees running at 2/3 of the peak, i.e. 32 GB/s. This is probably what happened in your double rack experiment. To avoid that issue, having different switches per groups of NIC (i.e. 2 parallel rails in your case) instead of per group of nodes helps a lot, but that needs to be considered when designing the fabric and cabling. The other solution to that static routing issue is to set up adaptive routing (which NCCL 2.6 now supports). In any case, and in particular for systems with multiple NICs, I would suggest working with your fabric provider to make sure the fabric is well designed and configured for NCCL.

**Comment by christopherhesse** [comment]
By "very large sizes" do you mean large message size or large number of nodes?

Nice to know it will automatically choose tree/ring correctly.

We'll work with the fabric provider, thanks for the tip!  Would adaptive routing likely avoid the three flows on one link issue?

**Comment by sjeaugey** [comment]
I meant large message size. And yes adaptive routing is supposed to solve exactly that problem.

**Comment by christopherhesse** [comment]
Thanks again!
