### ISSUE TITLE
Related hardware datapath

### ISSUE THREAD

**Issue by Isaacleee** [NVIDIA/nccl#336]
In terms of hardware, I want to know how work allreduce.

When we see the code, allreduce save the result of reduction at the next gpu. How it works they did not go through the local memory and result of data was saved to next gpu memory.

SMs interconnects with dma or Caches interconnects with dma. or Is there any other hardware to support these process?

I can't figure out how it works in terms of ''hardware''

thanks

**Comment by sjeaugey** [comment]
CUDA lets you access remote GPU memory directly through loads or stores. See `cudaDeviceEnablePeerAccess()`.
From within a process we call `cudaDeviceCanAccessPeer()` to allow a GPU to access the memory of another one; between processes `cudaIpcOpenMemHandle()` will automatically enable peer access with the `cudaIpcMemLazyEnablePeerAccess` flag.

How the hardware will effectively perform load/stores to the remote GPU is platform dependent. It will use NVLink if there is NVLink connectivity between the two GPUs, otherwise the loads/stores will go through PCI.

In any case, the GPU virtual memory mappings will be set by the GPU driver so that accesses to remote GPU memory use the right path. If there is no path, then the functions above will fail when trying to enable peer access between the GPUs.

**Comment by Isaacleee** [comment]
oh thanks.

One more questions, If cudaDeviceEnablePeerAccess() can available direct access to remote gpu memory, I want to know the more detail.

Right after reduction in local gpu, result of data go through 
1) SM -> NVLINK -> remote GPU memory
2) SM -> temporal buffer -> NVLink -> remote GPU memory
3) something else..

Didn't they go through  cache?

Thanks

**Comment by Isaacleee** [comment]
thanks!

**Comment by ihchoi12** [comment]
Hi @sjeaugey, thanks for your informative comments!

I wonder what happens if a GPU tries to access the other GPU on a different node.
Does NCCL detect it by looking at the socket address? 
Assuming GPU Direct RDMA is not available, does it copy the data to CPU first, and then CPU sends it through the network?

Thanks a lot!
