### ISSUE TITLE
Some doubts in Tree and CollNet.

### ISSUE THREAD

**Issue by Sikesky** [NVIDIA/nccl#372]
When I view the source code, I have some doubts in Tree and CollNet.
For Tree, here is a comment `Reduce : max number of recv is 3 (binary tree + local)`, what the `local` mean? In my understanding, rank which is not a leaf should recieve data for its two children and reduce with its data in sendbuff, but it will reduce 4 values when **NRECV** was set by 3. Where does the 4th value comes from?
For CollNet, first half of the channels do reduce and the second half of the channels do broadcast, how every rank get the correct result? In my understanding, Tree algorithm do allreduce by two steps: (1)**Reduce**, start from leaves and finally store the correct result in the root rank. (2)**Broadcast**, root rank will broadcast the result to all other ranks after (1) done. But CollNet seem not do the same, issue#320 had explained how CollNet works, but I still confuse about it.

**Comment by sjeaugey** [comment]
The binary tree is only how we communicate inter-node. But we can have an extra child the intra-node chain (node `local` rank). That's why we don't use trees on PCI platforms for large sizes : it becomes a ternary tree PCI-wise which is no longer able to achieve full bandwidth. On NVLink platforms however, it is a binary tree PCI-wise + a chain through NVLink so there is no bottleneck.
Adding the user buffer, indeed we might reduce up to 4 values.

For Collnet, each rank runs both the reduce and broadcast channels concurrently. And contrary to trees which currently performs a reduce, then a broadcast, collnet performs a continuous reduce and broadcast, with data flowing continuously through the reduce chain intra-node, then the network, then the broadcast chain intra-node. We could in fact implement trees the same way, having both the reduce and broadcast channels running in a continuous flow, to avoid having to re-load data from the root user buffer during the broadcast phase.

**Comment by Sikesky** [comment]
Thanks for the reply, now it's more clear to me. Another question is that LL mode seems to only get 50% maximum bandwidth of the peak(because 50% of the payload is the flag), but when I step in, I find that simple mode have 4x bandwidth compare to LL mode(LL mode get 1.5GB/s when simple mode get 6GB/s ), why is it?

**Comment by sjeaugey** [comment]
This is mostly because of optimization. LL is optimized for small messages, so it is not as unrolled as other protocols (and unrolling tends to increase latency).

**Comment by zgsbughammer** [comment]
> For Collnet, each rank runs both the reduce and broadcast channels concurrently. And contrary to trees which currently performs a reduce, then a broadcast, collnet performs a continuous reduce and broadcast, with data flowing continuously through the reduce chain intra-node, then the network, then the broadcast chain intra-node. We could in fact implement trees the same way, having both the reduce and broadcast channels running in a continuous flow, to avoid having to re-load data from the root user buffer during the broadcast phase.

Hi, @sjeaugey are reduce and broadcast running(pipelining) in a continuous flow for Tree algorithm now?
