### ISSUE TITLE
which part of the code calls netSendProxy?

### ISSUE THREAD

**Issue by zarzen** [NVIDIA/nccl#376]
Hi there,
I want to learn more about the implementation details of NCCL.
Specifically the network part for data transmission. 
Could you point me where does the `netSendProxy` function has been invoked? 
(I believe this is the delegator for NCCL to invoke socket calls) 
Simple search for `netSendProxy` didn't give me the results. 
I have also tried to check the `ncclPrimitives.send` implementation ([here](https://github.com/NVIDIA/nccl/blob/v2.4.8-1/src/collectives/device/primitives.h#L252)), while I didn't find any clue how the kernel function interact with networking.

**Comment by sjeaugey** [comment]
The netSendProxy and netRecvProxy are called in the persistent thread [here](https://github.com/NVIDIA/nccl/blob/master/src/proxy.cc#L195).

That progress function was set to `transportComm->proxy` [here](https://github.com/NVIDIA/nccl/blob/master/src/proxy.cc#L105).

And the `transportComm` field was set to either the send or receive sub-struct of the net transport as defined [here](https://github.com/NVIDIA/nccl/blob/master/src/transport/net.cc#L380).

The CUDA code does not communicate through the network. It only sends data to the proxy through a FIFO (or receives data from the proxy from a FIFO) using the same protocol as for inter-GPU communication. Which is why it is called a network proxy : it is almost transparent for the CUDA code. The only difference when interacting with a proxy (vs a GPU) is the use of [size FIFOs](https://github.com/NVIDIA/nccl/blob/v2.4.8-1/src/collectives/device/primitives.h#L121).

**Comment by zarzen** [comment]
Hi @sjeaugey, thanks for your pointers. 
One thing still confuses me that once we posted the size into [size FIFOs](https://github.com/NVIDIA/nccl/blob/v2.4.8-1/src/collectives/device/primitives.h#L121), how does the network layer ensure the data is ready? I see the state of `ncclProxyArgs* op` will be changed at the [saveProxy](https://github.com/NVIDIA/nccl/blob/v2.4.8-1/src/transport.cc#L109).
I think even though there is a `exitIfAbortBarrier(abort);` call before posting the size at [here](https://github.com/NVIDIA/nccl/blob/v2.4.8-1/src/collectives/device/primitives.h#L173). 
I feel it is possible to have the network layer start before the CUDA thread post the size. 

Another question is about the recv side, seems no corresponding function called `postRecvSzie`, I guess for receiving nccl can compute the size of the buffer for receiving. But how could nccl know for a certain data pointer for receiving is actually ready? Could you describe a little bit of the protocol you designed for communication?

**Comment by sjeaugey** [comment]
The protocol with the proxy is the same as between GPUs. We use a counter (tail) or the data itself (for LL*) to know data is ready.

On the receive side, we always receive a full slot with the maximum size. The receiving GPU, however, knows how much to receive so the proxy doesn't really need to know.

**Comment by zarzen** [comment]
Is there any document for describing the protocol for data exchanging between GPUs? 

So for the receiver side, the proxy always receives and puts the same amount of data into `CollectiveArgs->ThisOutput`?, then the GPU fetch part/all of the buffer?

**Comment by sjeaugey** [comment]
No, unfortunately at this point we never wrote a detailed document explaining the protocols. But it's basically a circular FIFO with head/tail counters.

The receiver does not receive the full slot, only what the sender sends. The sender transmits the size along with the data so that the receiver proxy knows when everything is received.

**Comment by zarzen** [comment]
Really thanks for the responsiveness!

I noticed that for doing `all_reduce` for a buffer, NCCL will progress based on grid-size=`nranks*loopSize`. 
And each rank will process one chunk inside the grid currently working on. For each chunk, there are 256 Cuda threads for reducing and copying data around. Those 256 threads are grouped into warps (32 threads each). 

I am specifically curious once threads completed their job, and the last thread-256 posted the size into sizeFIFO at [here](https://github.com/NVIDIA/nccl/blob/v2.4.8-1/src/collectives/device/primitives.h#L174), which part of the code is monitoring the sizeFIFO for sending out the data through the network? Thanks!

**Comment by sjeaugey** [comment]
The sizeFIFO is not the most important part. The tail index is used to notify data is ready. [Here](https://github.com/NVIDIA/nccl/blob/master/src/transport/net.cc#L240) is the proxy part, and [here](https://github.com/NVIDIA/nccl/blob/v2.4.8-1/src/collectives/device/primitives.h#L117) is the GPU part.

**Comment by zarzen** [comment]
Thanks a lot!
