### ISSUE TITLE
CUDA_VERSION instead of __CUDACC_VER_{MAJOR,MINOR}__?

### ISSUE THREAD

**Issue by Yangqing** [NVIDIA/nccl#38]
Just out of curiosity, is there a reason we infer CUDA_VERSION out of libcudart.so, instead of **CUDACC_VER_MAJOR** and **CUDACC_VER_MINOR** defined by nvcc? I am curious mainly because having CUDA_VERSION figured out via shell script makes it kind of hard to compile in a separate environment without manually feeding in these macros.

**Comment by nluehr** [comment]
NVCC's version variables are conveniently available during compilation, but the version is also needed at the shell level to build deb packages. I suspect this use case is what led to the current mechanism.

An alternative might be to derive the version from the output `nvcc -V` instead of libcudart's version. I'm not sure if this would be an improvement, without understanding better what environments you have in mind. You'd still need to locate libcudart in order to link. Also, if you want to build using different CUDA toolkits, you can export CUDA_HOME to the toolkit path, and all other directories should get set accordingly.

**Comment by sjeaugey** [comment]
Sorry, I missed this issue. Nathan is right regarding the initial reason behind the CUDA version detection.

I agree we could support your case, where CUDA is already in the PATH and therefore you don't need to set CUDA_HOME.

The new Makefile was supposed to be easier to integrate in any build environment (mostly all variables can be redefined) but maybe we have a regression on that aspect.

Would it be an acceptable solution for you to set CUDA_HOME ? 

If there is no easier/cleaner way, I guess you can always set CUDA_HOME with :
```
CUDA_HOME=$(dirname $(dirname $(which nvcc)))
```

**Comment by sjeaugey** [comment]
Cleaning up old bugs. Please reopen if it is still a problem. Thanks !
