### ISSUE TITLE
 nccl Ring All-Reduce 

### ISSUE THREAD

**Issue by Hamidreza-Ramezani** [NVIDIA/nccl#390]
Hello everyone! 

I had two questions regarding [this](https://github.com/NVIDIA/nccl/blob/de49a77074e884758e689ff0204f066eac7aae46/src/collectives/device/all_reduce.h#L56) line of the RingAllReduce kernel. I was wondering if you can help:

- In this line, as far as I understood, a chunk will be received and another chunk will be sent. I like to make sure whether these two chunks are different?
- I guess each device needs to store the partial accumulated result. Do they store them in thisInput variable, i.e, is thisInput updated after each step? If not, where partial results are stored? 

Thanks in advance!

**Comment by sjeaugey** [comment]
The mentioned line is reducing two chunks (one from the previous GPU, one local from `thisInput`) and sending the result to the next GPU. The partial reduction is not stored locally, it is only sent to the next GPU in the ring.

**Comment by Hamidreza-Ramezani** [comment]
Thank you very much for the reply. 

According to some online resources that I have seen, in step _i_ of the ring all_reduce algorithm, process _p_ sends the chunk _p - i_  to the next process and receives chunk _p - i - 1_ from the previous process in the ring. 

According to your implementation, I was wondering whether that specific chunk which is received (and then reduced and sent) is the chunk _p - i_ ?

**Comment by sjeaugey** [comment]
Intermediate FIFOs in NCCL are continously rotating and their index therefore depends on what happened before. The offset in the FIFO is no longer related to the step in the collective like it was before (probably up to 2.3).

We receive data from **step-1** of **rank-1**, so to ensure that data is coming from the same offset as the offset we process on the **rank** on **step**, the offset formula has to be based on something like "rank-step", so that (rank-1)-(step-1) lands at the same offset.

So I would not describe the chunk received as _p - i - 1_ but _(p-1) - (i-1)_ as it is coming from process _p-1_. The received chunk is therefore, with that notation, _p-i_.

**Comment by Hamidreza-Ramezani** [comment]
Thanks a lot Sylvain!
