### ISSUE TITLE
Difference between Unified Memory and NCCL

### ISSUE THREAD

**Issue by mfbalin** [NVIDIA/nccl#433]
Let's say I have an object in a managed pointer. If I access this object from multiple GPUs, it should work because I am using Unified Memory. However, what will be the speed of such an operation? Would using NCCL to do broadcast speed things up?

**Comment by sjeaugey** [comment]
It would depend on the size of the object, the number of times it is accessed, the bandwidth available between GPUs, ...

Or basically, how much time it costs your code to access this object remotely vs the NCCL broadcast time. You can find the NCCL broadcast time easily running the NCCL perf tests at the size you are interested in. For the extra time it costs your code because of remote access, I'm afraid this is application specific.

**Comment by mfbalin** [comment]
What if the object is very large > 1GB and I would like to broadcast it to all GPU's. The reason why I need to broadcast it is that I would like to store parts of the same large objects on different GPUs and broadcast it to all GPUs when needed. In this case, would using NCCL be faster? If I want to do the same thing via Unified Memory, how can I make it so that the broadcasted object is evicted from memory after their use from the other GPUs?

**Comment by sjeaugey** [comment]
Unfortunately this is something that is application specific, so we can only provide primitives which are moving data as fast as we can. Whether the best strategy for your needs is to migrate, replicate, distribute, access the data in place, or any combination of those is something the developers need to decide on based on what works best for them.

Which library or function to use to achieve that is also up to the developer, based on the capabilities of each. For example, simple CUDA operations could work fine for a single system, while NCCL/MPI will let you scale to more than one system using the network.
