### ISSUE TITLE
How to decide the right number of NCCL channels?

### ISSUE THREAD

**Issue by pro-panda** [NVIDIA/nccl#438]
How do channels work? (for a TCP/IP setup)
* How is more channels different from more socket threads?
* How does NCCL decide the right number of channels to use?

**Comment by pro-panda** [comment]
> 2 currently, to ensure proper overlap and no bubbles

Sorry, I didn't understand this

> This will split the transfers equally on each channel, which means the speed will be limited by the **socket having the lowest bandwidth**. We tried to have some dynamic balancing over multiple sockets, but none of our attempts worked.

Shouldn't all sockets have similar bandwidths?

**Comment by pro-panda** [comment]
> 2 currently, to ensure proper overlap and no bubbles

Sorry, I didn't understand that?

From the docs,
> However, the product of NCCL_SOCKET_NTHREADS and NCCL_NSOCKS_PERTHREAD cannot exceed 64

Why is that?

**Comment by sjeaugey** [comment]
On a channel, there can be communication bubbles where no communication is happening, e.g. because we are flushing data or synchronizing. Having two channels per NIC makes the NIC utilization closer to peak.

I imagine the limitation to 64 is because there is some static array of 64. It shouldn't be hard to increase if needed.

**Comment by pro-panda** [comment]
Thanks!
