### ISSUE TITLE
ncclTopoCompute function logic details

### ISSUE THREAD

**Issue by Richie-yan** [NVIDIA/nccl#454]
When reading the nccl code, I saw that the ncclTopoCompute function is used to build the final Topo, but the function is relatively complex. Can you help analyze the specific code logic of this function? The main points are the following two:
1. How is the nchannels of this function calculated?
2. What is the processing logic of this function for different network cards?
Any advice would help, thank you.

**Comment by sjeaugey** [comment]
I agree the function is complex. It is the intra-node search which tries to find a certain number of channels within the node, running at a given speed.

If the communicator extends beyond the node, then instead of starting with a GPU, the search will start with one NIC, go through all GPUs, and exit from the NIC.

You can dump what the search found with `NCCL_GRAPH_DUMP_FILE=graph.xml`.
