### ISSUE TITLE
RDMA without GPUDirect?

### ISSUE THREAD

**Issue by pro-panda** [NVIDIA/nccl#465]
This issue is more to do with configuring Mellanox drivers than NCCL.

I'm running a 4-node setup with 100Gbps IB supporting Mellanox cards, CUDA 10.2, Mellanox OEFD 4.4. I'm getting a bus bandwidth of 6GBps with nccl-tests, which is half of what I expected. I've tried NCCL 2.4.8, 2.5.7, master. No change in bandwidth.

I've installed the libibverbs drivers (without which I was getting 4GBps (IPoIB)). I've not setup nv_peer_memory module (https://github.com/Mellanox/nv_peer_memory/ - which would've enabled GPUdirect) since I'm facing issues with that.

Is it possible that NCCL is using RDMA without GPUDirect (CPU-CPU RDMA and then send/recv with GPU)? If yes, can I verify that? Otherwise, how do I debug the cause of the poor performance?

**Comment by sjeaugey** [comment]
Hi,

The performance you'll get is highly dependent on your PCI topology, i.e. how the NICs and GPUs are connected to each other. Can you share the topology of your node (run with `NCCL_TOPO_DUMP_FILE=system.txt` then attach the file here) ?

GPU Direct RDMA is not required in many cases; if we have to go through the CPU for NIC-GPU communication, we will use simple GPU->CPU and CPU->NIC communication, as this path is usually better optimized by CPU vendors (CPU are very, very bad PCI switches).

The one case where GPU Direct RDMA is needed is when the NIC and GPU are on the same PCI switch. In that case, you want data to go directly between the NIC and GPU through the switch instead of going up the link to the CPU twice, which would effectively halve the bandwidth.

If that is your case, then getting nv_peer_mem to work might be the key to getting better performance. To verify what NCCL is doing, you can set `NCCL_DEBUG=INFO` and look for lines like  `via NET/IB/0` or `via NET/IB/0/GDRDMA` (if using GPU direct RDMA).

**Comment by pro-panda** [comment]
[system.txt](https://github.com/NVIDIA/nccl/files/5963725/system.txt)

**Comment by sjeaugey** [comment]
It seems you are running inside a VM. The reported PCI topology is virtual (and flat), so NCCL cannot determine the topology correctly, and which NIC to use with which GPU.

That said, and beyond the topology (which would need to be properly reflected or defined in an XML file you can pass to NCCL), getting GPU Direct RDMA to work within the VM also requires proper configuration of the Hypervisor/PCI/..., so you should probably work with your VM / Cloud provider to allow GPU Direct RDMA inside the VM, and also reflect the topology inside the VM for NCCL to consume.

**Comment by pro-panda** [comment]
Thanks, I'm getting in touch with my cloud provider.

An interesting result that I noticed with RDMA without GPUDirect,
* 2 nodes, 8 GPUs per node, I get bus bandwidth of 9GBps
* 4 nodes, 8 GPUs per node, the bus bandwidth drops to 6GBps

Running a bandwidth test like iperf/ntttcp over the ib interface shows,
Node X -> Node Y bandwidth == 71Gbps
Node X <-> Node Y (bi-dir) == 48Gbps

Based on the ntttcp results, I can understand why bandwidth drops in the 4-node setup, but I'm surprised why it doesn't drop in the 2 node setting, since that would also use the bi-directional bandwidth. Any suggestions?

**Comment by pro-panda** [comment]
Thanks!
