### ISSUE TITLE
How All-Reduce async launch using in Pytorch

### ISSUE THREAD

**Issue by iamshlee** [NVIDIA/nccl#498]
In pytorch, they told pytorch can launch the asynchronous all-reduce. 
Also, I can see the all-reduce launch asynchronously in Profiler.

How one fastest launch all-reduce can wait for the other all-reduce launch from other devices. I want to know how it can be implemented.

I want to know if it is pytorch or nccl that controls this. If so, I want to know where it is implemented.

Thank you

**Comment by sjeaugey** [comment]
Indeed, when running NCCL concurrently with other compute workload on the GPU, it is important that NCCL starts at the same time on all GPUs, otherwise most GPUs would be waiting for the last GPU to start and waste GPU time.

This is not very easy to ensure, as it's a combination of CPU-side timing, to make sure NCCL/non-NCCL CUDA kernels are posted in the same order on all GPUs, and CUDA scheduling kernels the same way on all GPUs.

NCCL can't do much about it in any case, and this is all about how the framework does its CUDA scheduling (which I'm not expert enough to comment on).

**Comment by iamshlee** [comment]
Thanks for your help!!
