### ISSUE TITLE
What is the need for exchanging size?

### ISSUE THREAD

**Issue by rahul-bothra** [NVIDIA/nccl#515]
What is the need for exchanging size in NCCL socket implementation?
Is it only to check if the expected size matches with the size being sent?

NCCL hangs if I remove the follwoing size exchange code,
https://github.com/NVIDIA/nccl/blob/3fec2fa5eea34917f09e2282afc38863b454eae1/src/transport/net_socket.cc#L407-L421

Comment on L411 says "Not ready". What is it referring to?

**Comment by rahul-bothra** [comment]
@sjeaugey any suggestions?

**Comment by kwen2501** [comment]
The exchange is there because the actual send size can be smaller than the "receive size" posted by the network receive proxy which is simply a size of a buffer slice corresponding to an algorithm + protocol combination.

Regarding the "Not ready" comment, `socketProgres` is non-blocking, so here "not ready" means the transfer of the size has not finished.

**Comment by rahul-bothra** [comment]
Thanks!
