### ISSUE TITLE
NCCL hang when invoking ncclAllReduce and ncclSend/Recv concurrently

### ISSUE THREAD

**Issue by xutianming** [NVIDIA/nccl#522]
Dear developers,

I was invoking nccl api concurrently using separate communicator & cuda stream.
NCCL happened to hang the GPU with following stacks.

![image](https://user-images.githubusercontent.com/4970790/122176948-b8d16600-ceb7-11eb-89d0-953f46053bc5.png)
![image](https://user-images.githubusercontent.com/4970790/122177065-d999bb80-ceb7-11eb-9d1c-577011a6dc08.png)
![image](https://user-images.githubusercontent.com/4970790/122177114-e4545080-ceb7-11eb-9c8e-ddf72a1398a4.png)

**Comment by sjeaugey** [comment]
There is a possibility to get a hang when running two NCCL operations concurrently. Using different CUDA streams does not guarantee operations will run concurrently.

The backtrace on the CPU side won't tell us much about the hang if the problem is on the GPU side; you might want to use cuda-gdb to look at the GPU side.

**Comment by xutianming** [comment]
@sjeaugey Thanks for your advice. I tried cuda-gdb but I only got one-line backtrace of ncclSendRecv
![image](https://user-images.githubusercontent.com/4970790/122224893-22b53400-cee7-11eb-899b-a1b037b07a57.png)

I used backtrace. How could I get more information about the hang ?

**Comment by xutianming** [comment]
Experiment 2

To avoid not having enough free CUDA SMs to launch 3 NCCL kernels concurrently, I set NCCL_MAX_NCHANNELS & NCCL_MIN_NCHANNELS to 1.

![image](https://user-images.githubusercontent.com/4970790/122228785-c6541380-ceea-11eb-8bf5-d1d320dbf059.png)

![image](https://user-images.githubusercontent.com/4970790/122228823-cfdd7b80-ceea-11eb-8745-b4d438aaf29f.png)

**Comment by xutianming** [comment]
> If some GPUs are running ncclSendRecv first, then ncclAllReduce while others do the opposite, it is expected that you end up with a deadlock. Running two NCCL operations concurrently is never guaranteed to work.

Even if I use two NCCL communicator and cuda stream,  two NCCL operations is not guaranteed to work ? Right ?

**Comment by sjeaugey** [comment]
> @sjeaugey
> Even if I use two NCCL communicators and cuda streams, running two NCCL operations concurrently is not guaranteed to work ? Right ?

That is correct. CUDA does not give guarantees that two asynchronous streams will effectively run independently of each other. They may still block each other.

**Comment by nevion** [comment]
@sjeaugey  is that the case even with just cudaMemcpyAsync or cudaEventWaits or is it just the case with the kernels you're using?

**Comment by sjeaugey** [comment]
For cudaMemcpyAsync, I think it is the same; we may end up starting a CUDA kernel to process the copy. Not sure whether it could happen in practice, it's probably implementation dependent.
For cudaStreamWaitEvent it's a bit different since it's only expressing a dependency between two streams; there is no work to progress (concurrently or not).
