### ISSUE TITLE
Why NCCL do not create intra-node tree?

### ISSUE THREAD

**Issue by dearsxx0918** [NVIDIA/nccl#532]
NCCL now use a double tree or ring as virtual topology. But the double tree only create on node level(inter-node), is there any concerns or performance reduction if intra-node tree?

**Comment by sjeaugey** [comment]
Intra-node tree could be better for latency; for bandwidth it might be tricky to make it work on all topologies. Beside, intra-node, the LL128 protocol pipelines data very well so that it's actually really hard to beat.

So, while Intra-node tree would probably give slightly better latencies for extremely small sizes (e.g. 8B), whether it can give a significant performance gain on a range of sizes we care about is still very uncertain.

**Comment by dearsxx0918** [comment]
Thanks for you replay!
