### ISSUE TITLE
How NCCL combines Tree and Ring?

### ISSUE THREAD

**Issue by void-main** [NVIDIA/nccl#548]
In the GTC talk, you mentioned NCCL handles intra-node communication with rings and inter-node communication with double binary tree.

I wonder how you implement this in code? Could you please point out the related code?

**Comment by void-main** [comment]
To make the question more specific, say we're using 4 DGX-A100 (8 GPUs with 8 NICs) boxes, and we're using (Balanced-)TREE algorithm for all-reduce, then:

1. how many nodes are in the tree? is it 4 (1 GPU from each node) or 32 (all GPUs) or 8 (2 GPUs from each node)?
2. are there any rings built under the hood? if so, could you please kindly point the code out? (based on the code, I don't see any ring-like operations in `runSplitTree` function)
3. will NCCL perform intra-node reduce-scatter, inter-node all-reduce, and intra-node broadcast sequentially? If so, could you please point out the code as well?

For ring method, I can tell there's a special "proxy" memory in the ring, and everything just works. But for the tree, I'm pretty confused, could you please give me some hints. Thank you very much!

**Comment by sjeaugey** [comment]
1. There are 4 nodes in each tree, but on each node we might be using 1 or 2 GPUs to send or receive date, depending on the cases. In the case of DGX-A100 indeed instead of having the same GPU send to 2 nodes, the two GPUs close to the NIC send to one node each. From the network perspective, data is coming from the same node and same NIC, but intra-node we pull data from two GPUs.
2. We don't really use rings intra-node, more like a chain, going through each of the 8 GPUs, and finishing by the two GPUs close to the NIC. For example, for NIC 0, data for a reduce would flow like this:
```
 GPU7->GPU6->GPU5->GPU4->GPU3->GPU2->GPU1->GPU0-> GPU0/up
                          GPU0/down0 --^     ^-- GPU0/down1
```
Computing the tree and up/down[] ranks is pretty complex and starts from the graph search for intra-node (`graph/search.cc`) then the tree connect (`graph/connect.cc`).
3. For each channel, it's an intra-node chain reduce, pipelined with an inter-node allreduce, pipelined with an intra-node chain broadcast. If you look at all channels together though, you could see that as a reduce-scatter (8 reduces converging to different GPUs), coupled to 8 inter-node allreduce, coupled to an allgather (8 broadcasts originating from different GPUs). But that needs some imagination.

**Comment by void-main** [comment]
Thanks for such detailed explanation!
