### ISSUE TITLE
How to throw an exception when the program is stalled in a point-to-point operation?

### ISSUE THREAD

**Issue by ConnollyLeon** [NVIDIA/nccl#593]
I am trying to implement a NeighborExchange operator, which means different devices may have different numbers of NcclSend and NcclReceive operations. 

I notice that if the number of NcclSend and NcclReceive are not equal, the program will be stalling and won't exit. 

I wonder how to throw an exception when the program is stalling, so that we could notice our users that in their code, global send number is not equal to global  receive number?

**Comment by sjeaugey** [comment]
I'm not sure I understand the request. Are you asking for NCCL to detect that condition and return an error, or some other functionality?

**Comment by jbachan** [comment]
NCCL is not in the best position to detect this kind of deadlock. From NCCL's perspective, even if things seem stuck, there is no way we can be sure that the missing send/recv will never arrive no matter how long we wait since we don't know the global properties of your communication pattern. Your library is in a much better position to do this. For example, after injecting all ncclSend/Recv's you could execute an allreduce on the host CPUs (using MPI or some other CPU-side parallel algorithm library) to tally the number of posted sends and recvs from each rank. When that reduction comes back you'll have the information needed to prove that the communication pattern is incomplete (for instance if TotalSends != TotalRecvs) and can raise the appropriate error to your user.

**Comment by ConnollyLeon** [comment]
Thanks for all your replies.

> I'm not sure I understand the request. Are you asking for NCCL to detect that condition and return an error, or some other functionality?

@sjeaugey Exactly.



> NCCL is not in the best position to detect this kind of deadlock. From NCCL's perspective, even if things seem stuck, there is no way we can be sure that the missing send/recv will never arrive no matter how long we wait since we don't know the global properties of your communication pattern. Your library is in a much better position to do this. For example, after injecting all ncclSend/Recv's you could execute an allreduce on the host CPUs (using MPI or some other CPU-side parallel algorithm library) to tally the number of posted sends and recvs from each rank. When that reduction comes back you'll have the information needed to prove that the communication pattern is incomplete (for instance if TotalSends != TotalRecvs) and can raise the appropriate error to your user.

This seems to be a good solution, since NCCL cannot detect this kind of deadlock well. I think it would be better to do a AllReduce before we execute a NeighborExchange operation to check the Send num and Recv num are equal.

**Comment by zpcalan** [comment]
Besides hanging at Send/Recv or AllReduce, I found `ncclCommInitRank`  could also block the thread if one of the processes exits. I called  `ncclCommAbort` but it doesn't help. I guess it's because the communicator is not initialized until `ncclCommInitRank` returns. Is there also a way to fix this? @sjeaugey @jbachan

**Comment by sjeaugey** [comment]
> Besides hanging at Send/Recv or AllReduce, I found ncclCommInitRank could also block the thread if one of the processes exits. I called ncclCommAbort but it doesn't help. I guess it's because the communicator is not initialized until ncclCommInitRank returns. Is there also a way to fix this?

Indeed, that is a problem. If a process doesn't show up during ncclCommInitRank, we have a hang which we can't cancel. We are working on adding the ability to abort an init operation, but that requires API changes which could break API compatibility, which we're trying to avoid.

**Comment by zpcalan** [comment]
> Indeed, that is a problem. If a process doesn't show up during ncclCommInitRank, we have a hang which we can't cancel. We are working on adding the ability to abort an init operation, but that requires API changes which could break API compatibility, which we're trying to avoid.

Thanks, it's good to get your confirmation!

Maybe add a default arguement for `ncclCommInitRank` as timeout seconds? 
It's just an advice. This may cause compatibility issue, right?

**Comment by sjeaugey** [comment]
Yes this would break the API. Our current idea is to return immediately with a valid (but not yet initialized) `comm` object which you would be able to abort. The communicator would be initialized in background and the first call to a NCCL collective would block until initialization is done. If you want to check whether the communicator is initialized or not to avoid blocking on the first NCCL collective, you would have a new API to check the status of the communicator and abort if necessary/after a given timeout you would define.
