### ISSUE TITLE
nccl mpi communication

### ISSUE THREAD

**Issue by mengyuanxbox360** [NVIDIA/nccl#63]
Dear All:

I got some questions while testing the nccl/test/mpi/nccl_test.cu code. Firstly, does it support multi-workstation communication cross different workstations. Secondly, will it block the GPU computation during the nccl data communication(such as ncclallredue).  Thanks a lot.

Yours
Sincerely

**Comment by sjeaugey** [comment]
NCCL does not support inter-node communication. Also, it launches CUDA kernels on the user-provided stream, so that communication can be performed asynchronously and concurrently with other CUDA kernels.

**Comment by hiyijian** [comment]
Icome across same issuse.
Is there any graceful and efficient way to combine nccl and mpi for both inner-node and inter-node communication please? 
And will the nccl communication slow down other computing task in the case of parallel both?

**Comment by astooke** [comment]
How would it work?  Inter-node comm must go through CPU, right?  Seems reasonable to me to have each node pull values from GPUs to CPU and then use only MPI for inter-node communication, leaving NCCL out of it.

**Comment by nouiz** [comment]
Maybe there is some way to transfer directly from the GPU memory to the
network. I read stuff related to that. I don't know if it was theoretical
of if it work in practice. We didn't do that.

**Comment by astooke** [comment]
Hmm, my understanding is that NCCL pipes data through the CPU when GPUs aren't on the same PCIe bus already, so maybe it's actually not that different to go inter-node.

But one very nice property of NCCL that not all MPI implementations share is the ability to set up the comm world without using a runner function like `mpiexec`.  Perhaps making NCCL inter-node would introduce too much dependency on MPI or else require a function like `mpiexec` to run it (please no!).

Anyway, I'll stop speculating...

**Comment by sjeaugey** [comment]
All, 

NCCL2 supports multi-node communication and is now available for download at https://developer.nvidia.com/nccl.

It does not depend on MPI but indeed if you want to run on multiple nodes, you will need *some* mechanism to manage the multiple processes and CPU-to-CPU communication, which is MPI is a good complement to NCCL2 when running across nodes.

**Comment by clustarycx** [comment]
Hi sjeaugey,

I need to do reduction across machines also. and I found NCCL can do that.
When I went through the API of NCCL, I found the reduce functions only work with data pointers.

ncclResult_t  ncclAllReduce(const void* sendbuff, void* recvbuff, size_t
        count,
     ncclDataType_t datatype, ncclRedOp_t op, ncclComm_t comm, cudaStream_t
        stream);

2.3. Data Pointers
In general NCCL will accept any CUDA pointers that are accessible from the CUDA device associated to the communicator object. This includes:
device memory local to the CUDA device
host memory registered using CUDA SDK APIs cudaHostRegister or cudaGetDevicePointer
managed and unified memory
The only exception is device memory located on another device but accessible from the current device using peer access. NCCL will return an error in that case to avoid programming errors (only when NCCL_CHECK_POINTERS=1 since 2.2.12).

But in multiple machines situation, how can I get the remote machine's addr?

And I saw Gloo is lib used to do reduction across machines, if NCCL2 can do this, why Gloo is still needed?

Thanks for your help.
