### ISSUE TITLE
Is it safe to reuse cudaStream_t?

### ISSUE THREAD

**Issue by hiyijian** [NVIDIA/nccl#64]
hi, all
  Is it safe to reuse a cudaStream_t object(say stream0) after cudaStreamSynchronize(stream0)?  More specifically, Is following code safe:
  ```c++
  cudaStream_t stream0;
  CHECK_EQ(cudaStreamCreateWithFlags(&stream0, cudaStreamNonBlocking), ncclSuccess);
  for(int i = 0; i < 1000000; ++i) {
    // communition
    CHECK_EQ(ncclAllReduce(src_ptr, dst_ptr,  some_count, ncclFloat,
                              ncclSum, some_comm, stream0), ncclSuccess);
     // do something else
     ...
     ...
    
     // wait it
     cudaStreamSynchronize(stream0)

     // without destory stream0
  }
  ```

**Comment by cliffwoolley** [comment]
This is really a CUDA question, not a NCCL question.

But yes, you can reuse CUDA streams.  Do be wary of the special semantics
of nonblocking streams, since your example happens to use them.  See the
CUDA docs for details.

Thanks,
Cliff

**Comment by hiyijian** [comment]
hi @cliffwoolley ,
   Thanks. But what do you mean by special semantics? Can you make it more clear?

**Comment by cliffwoolley** [comment]
http://docs.nvidia.com/cuda/cuda-runtime-api/group__
CUDART__STREAM.html#group__CUDART__STREAM_1gb1e32aff9f59119e4d0a9858991c4ad3
gives a short version of it.  Basically nonblocking streams never
synchronize with other streams unless you specifically tell them to.  This
can sometimes be exactly what you want, but it's also easy to make a
mistake in using this functionality that can lead to subtle race
conditions.  For example, if you accidentally launch a kernel that was
supposed to go into that stream using <<<x,y>>> instead of <<<x,y,z,w>>>
notation, then you're mixing the default stream with this special stream.
With regular streams, the result is correct if perhaps suboptimal.  With
nonblocking streams, the result is nondeterministic.  So just be careful.
 :)

-Cliff

**Comment by hiyijian** [comment]
Thanks @cliffwoolley
