### ISSUE TITLE
NCCL crash when running Megatron-LM

### ISSUE THREAD

**Issue by manjunaths** [NVIDIA/nccl#653]
I am trying to run Megatron-LM gpt on multiple nodes. When I set NCCL_ALGO=CollNet, the training code crashes, with the following error,
```
201:
201: :41367:41367 [1] enqueue.cc:422 NCCL WARN Error : no algorithm/protocol available
201: Traceback (most recent call last):
201:   File "/home/user/Megatron-LM-hp/pretrain_gpt.py", line 124, in <module>
201:     pretrain(train_valid_test_datasets_provider, model_provider,
201:   File "/home/user/Megatron-LM-hp/megatron/training.py", line 96, in pretrain
202:
202: :41368:41368 [2] enqueue.cc:422 NCCL WARN Error : no algorithm/protocol available
201:     initialize_megatron(extra_args_provider=extra_args_provider,
255:
255: :62797:62797 [7] enqueue.cc:422 NCCL WARN Error : no algorithm/protocol available
201:   File "/home/user/Megatron-LM-hp/megatron/initialize.py", line 88, in initialize_megatron
251:
251: :62793:62793 [3] enqueue.cc:422 NCCL WARN Error : no algorithm/protocol available
201:     _compile_dependencies()
201:   File "/home/user/Megatron-LM-hp/megatron/initialize.py", line 139, in _compile_dependencies
201:     torch.distributed.barrier()
201:   File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2654, in barrier
253:
253: :62795:62795 [5] enqueue.cc:422 NCCL WARN Error : no algorithm/protocol available
201:     work = default_pg.barrier(opts=opts)
249:
249: :62791:62791 [1] enqueue.cc:422 NCCL WARN Error : no algorithm/protocol available
201: RuntimeError: NCCL error in: /opt/pytorch/pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:42, internal error, NCCL version 21.1.4
201: ncclInternalError: Internal check failed. This is either a bug in NCCL or due to memory corruption

```

When I remove the setting NCCL_ALGO, it runs but the elapsed time increases with the doubling of the global batch size,

And I get a warning like this,
```
24: :14762:18263 [0] transport.cc:238 NCCL WARN Cannot initialize CollNet, using point-to-point network in
stead
```
I am expecting that the elapsed time should remain the same or reduce when I scale. 

I ran the NCCL benchmark all_reduce and broadcast_perf with NCCL_ALGO set to CollNet and without and it seems to run fine. This is for the same set of nodes too.

Any ideas of what might be wrong ? Thanks.

**Comment by sjeaugey** [comment]
It seems you're forcing CollNet on a communicator which cannot use CollNet. I'd need the log with NCCL_DEBUG=INFO to have an idea of why the communicator cannot use SHARP.

**Comment by manjunaths** [comment]
Thank you for your reply. Here is the log file with the required variable set.
[1966_23node_256gpu_megatron.log](https://gist.github.com/manjunaths/151bee5eefb96df7b32c51acca233dcc)
The run script is the [gpt3 script](https://github.com/NVIDIA/Megatron-LM/blob/main/examples/pretrain_gpt3_175B.sh) with modifications to reflect the cluster environment.

Thanks.

**Comment by sjeaugey** [comment]
Sorry I wasn't clear. I needed the log of a run without NCCL_ALGO, so that we get the warning you described:
```
24: :14762:18263 [0] transport.cc:238 NCCL WARN Cannot initialize CollNet, using point-to-point network in
stead
```
Hopefully there will be some INFO before that explaining why SHARP setup failed and we had a fallback to rings/trees.

**Comment by manjunaths** [comment]
Thank you for your reply. [Here](https://gist.github.com/manjunaths/65290ec1006b87b399c12eb85412714b) is the log without NCCL_ALGO set.

**Comment by sjeaugey** [comment]
It seems you are exhausting SHARP resources because the application is creating more communicators than SHARP can handle. The first communicator with all 32 GPUs can use SHARP, but the small communicators created after that may be trying to use the NIC twice per node since you only have 1 NIC for 2 GPUs.

So everything is working as expected from what I can see.

Now it's not clear to me what communication patterns are. I see one 32-ranks communicator which includes all GPUs, then a lot of 2-ranks communicators. Model parallelism is probably responsible for those small transverse communicators but it's not clear which GPU communicates with which GPU. Understanding that better could help understand the communication bottlenecks and figure out what is preventing scaling. Also, it is usually useful to profile iterations to see what is the compute time (forward/backward), what is the communication time, and what is the update time. That is key to understanding and solving scalability issues.

**Comment by manjunaths** [comment]
Thank you for your help.

**Comment by RyoYang** [comment]
@manjunaths Hey Manjunath, have you fixed this issue finally? I encounter the same error when I would like to run distributed jobs by megatron-lm with sharp.
