### ISSUE TITLE
Why choose node 0 as root node in binary tree always ?

### ISSUE THREAD

**Issue by elevenxiang** [NVIDIA/nccl#673]
Hi, 

Currently , I am reading the double binary tree code.
And I found that the NCCL double binary tree is different from the mentioned paper.

In NCCL, it always chooses node 0 as the root node

So why ? obviously it makes the tree deeper

Thanks

**Comment by elevenxiang** [comment]
Question 2: why root node has only one child ?

Thanks

**Comment by elevenxiang** [comment]
My guess is that zero number is hard to manipulate through power of 2 ?
So first to generate the tree with other ranks, and after that just connect it under the node 0 ?

**Comment by elevenxiang** [comment]
anyone could help to answer this ?

**Comment by sjeaugey** [comment]
Sorry I missed it.

Trees are only implemented for allreduce at the moment. We can therefore choose whichever rank we want as the root of the tree, and even use different roots for different tree channels. 

And as far as I know we do use different roots. Each complementary tree has a different root (typically on the first and last nodes), and each NIC rail converges to a different GPU as well on the root nodes. So you should have 2*number of NICs roots where reduce operations converge and from where broadcast operations originate from in the opposite direction.

It is true that the root only has one child, and that's because we can afford it (we still won't have bottlenecks), and it makes our tree computation algorithm simpler and more regular. If you look at the drawing, it makes a very regular tree which keeps the same connections for most ranks as you scale, just adding an extra level when crossing a power of two.

**Comment by elevenxiang** [comment]
> Sorry I missed it.
> 
> Trees are only implemented for allreduce at the moment. We can therefore choose whichever rank we want as the root of the tree, and even use different roots for different tree channels.
> 
> And as far as I know we do use different roots. Each complementary tree has a different root (typically on the first and last nodes), and each NIC rail converges to a different GPU as well on the root nodes. So you should have 2*number of NICs roots where reduce operations converge and from where broadcast operations originate from in the opposite direction.
> 
> It is true that the root only has one child, and that's because we can afford it (we still won't have bottlenecks), and it makes our tree computation algorithm simpler and more regular. If you look at the drawing, it makes a very regular tree which keeps the same connections for most ranks as you scale, just adding an extra level when crossing a power of two.

@sjeaugey 
I think I didn't describe my question clearly.
When construct tree 0 of double binary tree, it always choose node 0 as the root from the code below:
[
](https://github.com/NVIDIA/nccl/blob/9bfc1c6e3587bd8f0dfadc42afd16dfad4ccd75c/src/graph/trees.cc#L31-L44)

so here is the question, why choose node 0 as root in tree 0 always ?

and of course tree 1 will have different root due to it will do mirror or shift

**Comment by elevenxiang** [comment]
and I have such a question because I found it have different algorithm from the paper, which your blog mentioned:
Peter Sanders; Jochen Speck, Jesper Larsson Träff (2009); Two-tree algorithms for full bandwidth broadcast, reduction and scan

**Comment by sjeaugey** [comment]
> so here is the question, why choose node 0 as root in tree 0 always ?
> and of course tree 1 will have different root due to it will do mirror or shift

As I mentioned, it's because it works well to build the binary trees from the pattern we describe in the blog entry, and which is regular, maps well to powers of two and have good locality.

The original paper was for broadcast, which means both trees need to have the same root as per the broadcast semantics. Since we're implementing allreduce, we do not have that constraint which gives us more freedom the in tree construction. Having roots at opposite sides also splits the traffic on both sides, lowering the risks of routing collision between flows of the two trees.

**Comment by elevenxiang** [comment]
> > so here is the question, why choose node 0 as root in tree 0 always ?
> > and of course tree 1 will have different root due to it will do mirror or shift
> 
> As I mentioned, it's because it works well to build the binary trees from the pattern we describe in the blog entry, and which is regular, maps well to powers of two and have good locality.
> 
> The original paper was for broadcast, which means both trees need to have the same root as per the broadcast semantics. Since we're implementing allreduce, we do not have that constraint which gives us more freedom the in tree construction. Having roots at opposite sides also splits the traffic on both sides, lowering the risks of routing collision between flows of the two trees.

Thank you so much
