### ISSUE TITLE
ncclNet plugin isend/irecv

### ISSUE THREAD

**Issue by arttianezhu** [NVIDIA/nccl#742]
Hello!

I'm implementing a custom ncclNet plugin to make use of CUDA buffers. I have a question w.r.t the semantics of the isend and irecv APIs. Is it possible for NCCL to send host buffers and expect to receive the data in cuda buffers? What about cuda buffer -> host buffer path?

A potentially related question is around this line: https://github.com/NVIDIA/nccl/blob/master/src/transport/net.cc#L541. IIUC, this means the LL protocol is restricted to host buffers only. (Why is this the case?) I believe this would basically create host buffer -> cuda buffer transfers for LL protocol.

Please help correct me for any misunderstandings. Thank you!

**Comment by sjeaugey** [comment]
> Is it possible for NCCL to send host buffers and expect to receive the data in cuda buffers?

Yes it is possible to send host buffers and receive in a CUDA buffer, and it is actually pretty common.
Consider a PCI platform with 8 GPUs, 2 sockets, one PCI switch per socket and one NIC on one side.

![PCI-IB-3](https://user-images.githubusercontent.com/12857445/198236773-193bc447-e3ca-4101-8b29-320e7ed6b646.png)

In a ring algorithm, the first GPU would receive data directly into its CUDA buffer (since the NIC and GPU are on the same PCI Switch) but the last GPU of the node would send data to the next node through the CPU, therefore using host buffers as intermediate step.

As for the LL protocol, it requires the CPU to check the flags within the data to know when data is ready to send through the network. Therefore, it never uses CUDA buffers on the sender side regardless of the node topology.

**Comment by sjeaugey** [comment]
1. LL128 is meant to have better latency than Simple and better bandwidth than LL. Using host memory would kill the bandwidth (as we'd have a bottleneck going through the CPU) so with LL128 we do the same as with Simple: we call threadfence then increase a flag on the host to tell the CPU data is ready to be sent. This has a higher latency than LL but the goals are different. LL is meant at getting the best latency, not bandwidth.
2. No, the protocol we pick is based on the size and we'll go from LL to LL128 to Simple as sizes grow. Each channels has GPU-GPU connections, and each connection consists in a single pair of head/tail indexes but all three buffers for LL, LL128 and Simple, buffers being located potentially in different places.

**Comment by arttianezhu** [comment]
I see! Thank you!
