### ISSUE TITLE
some more questions NCCL-2.14.3

### ISSUE THREAD

**Issue by hongbilu** [NVIDIA/nccl#763]
1. stream class naming, strongstream, why use it ? is there a weak stream?
2. if proxy use LL protocol to transfer data to peer node via GDR, when the peer receive it by not using polling_cq API, what I‘m confused is:  it that possible NIC hardware also generate CQE to the cq which can be overflow at last？
3. in prims_simple.h, what does template parameter “Unroll” mean? I noted that it as a array length “Pack128 vals[UNROLL]”
4. in ReduceCopy128bMulti, what is preOp and postOp meaning for kinds of redop?
5. about simple kernel sync question like code below:
if (tid < nworkers && offset < nelem) {
  do {
        ...
        barrier(); // This barrier has a counterpart in following loop
        if (Send && (flags & RolePostSend) && index == 0) __threadfence_system();  **//A. in worker threads, it seems no one's role is postsend, what does this code do?**
        __syncwarp();  **//B. I don't understand why warpsync needed here?**
        postPeer<Recv, Send>();  **//C. in worker threads, it seems no one's role is postsend/recv, what does this code do?**
        offset += sliceSize;
        slice += 1;
      } while (slice < SlicePerChunk && offset < nelem);
}

**Comment by jbachan** [comment]
1. There is no weak stream other than the regular CUDA stream. The strong stream is considered "stronger" because it doesn't lose its identity during CUDA graph capture. For example, say you record a CUDA graph `G` that launches a single kernel `K` against the captured non-strong stream `S1`, then launch `G` on non-strong stream `S2`. The result will be that `K` is launched on `S2` but `S1` isn't affected at all, anything launched on `S1` would run parallel with `K`. If `S1` is changed to a strong-stream, then `K`'s launch would be observed by both `S1` and `S2`, any subsequent launches on `S1` would be ordered after `K`. NCCL needs this internally since all of our collectives need to be serialized.

**Comment by hongbilu** [comment]
thanks for your answer. But I'm still confusing why __syncwarp is neccessary needed again after global barrier for worker threads, for question 5-B?

**Comment by jbachan** [comment]
5-B) Only one thread executes the threadfence (since `index==0`). But many of the threads in the warp could be posting credits, each to its designated peer, indicating that data is visible. The syncwarp ensures the threadfence is in the history of all threads in the warp so those credits will only be delivered after the threadfence returns.

**Comment by hongbilu** [comment]
thanks you, I know that what you said works for last Warp(non-worker threads), but for worker threads, there are also same code:
barrier(); // This barrier has a counterpart in following loop
        if (Send && (flags & RolePostSend) && index == 0) __threadfence_system();  **//A**
        __syncwarp();                                                                                                       **//B**
        postPeer<Recv, Send>();                                                                                     **//C**
but no workers threads whose role is postsend or postrecv, so line A and C do nothing here, so I think syncwarp here seems not to be neccesary, plz correct me if i misunderstand

**Comment by jbachan** [comment]
It isn't always the case that there is a dedicated non-work warp, sometimes a warp has to wear both hats. For instance, if the prims object is only given one warp (32 threads) to use, then that warp has to do everything. The `Primitives()` constructor inspects the thread count to determine if it can afford to dedicate a non-worker warp.
