### ISSUE TITLE
reduce hangs in NVLink version but no longer in public version

### ISSUE THREAD

**Issue by astooke** [NVIDIA/nccl#82]
Hi,

  I observed recently NCCL hanging at calls to reduce, for greater than 2 GPUs on a DGX-1, using the public NCCL.  This happened during `pygpu` calls to `reduce`, and the NCCL test `reduce_scan`, but it did not happen during `reduce_test`.  The symptoms were like those described in #37, except it was only for `reduce`.  A few days ago I pulled from here, which brought a few small updates, rebuilt NCCL, and it all works now.

 But when I try to use any docker image with NVLink-enabled NCCL, the issue remains.  (Although sometimes it works for up to maybe 5 GPUs during `reduce_scan`.)   Is there a container available in the registry with the NVLink version with this fixed?  :)

Thank you!
Adam

**Comment by sjeaugey** [comment]
Hi Adam,

Thanks for reporting this. It was indeed fixed in 8e1d6f9b60724ef38bb51dd17869be7c093332e8.

There is indeed no NVLink version with the fix (yet), but as the commit message implies, a simple workaround is to provide a valid recvbuffer for all ranks (not only the root).

Sylvain

**Comment by astooke** [comment]
Thank you for pointing out that commit to me!  I had not seen that, so I appreciate the workaround.

**Comment by cliffwoolley** [comment]
Hi Adam,

If there are changes you would like to request to software provided with
DGX-1, please contact the DGX support team with those requests.  We can
only cover the GitHub version of NCCL on this list.

Thanks!
Cliff

On Apr 4, 2017 9:52 AM, "Sylvain Jeaugey" <notifications@github.com> wrote:

Hi Adam,

Thanks for reporting this. It was indeed fixed in 8e1d6f9
<https://github.com/NVIDIA/nccl/commit/8e1d6f9b60724ef38bb51dd17869be7c093332e8>
.

There is indeed no NVLink version with the fix (yet), but as the commit
message implies, a simple workaround is to provide a valid recvbuffer for
all ranks (not only the root).

Sylvain

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/NVIDIA/nccl/issues/82#issuecomment-291562556>, or mute
the thread

**Comment by astooke** [comment]
@cliffwoolley Ok understood!  So in this case should I raise this issue with them or is it already known there?  The fix commit is from before the latest set of DGX-1 containers.

**Comment by cliffwoolley** [comment]
I wouldn't be able to comment on that.  Please take it up with DGX support
if it's important to you.  Thanks!
