### ISSUE TITLE
Questions about Primitives::genericOp

### ISSUE THREAD

**Issue by MonroeD** [NVIDIA/nccl#821]
NCCL versionv2.12.12
```
if (tid < nworkers && offset < nelem) {
   ...
  do { 
    barrier(); // This barrier has a counterpart in following loop
    if (Send && (flags & RolePostSend) && index == 0) __threadfence_system();
    __syncwarp();
    postPeer<Recv, Send>();
    offset += sliceSize;
    slice += 1;
  } while (slice < SlicePerChunk && offset < nelem);
}

 // Non-workers come straight here. Workers too but only once the remaining
 // slices are all empty. Since empty slices are the uncommon case, and
 // worker perf is the limiter, perf-wise this loop is effectively unentered,
 // hence just a single branch insn.
 #pragma unroll 1
 while (slice < SlicePerChunk) {
   sliceSize = sliceSize < nelem-offset ? sliceSize : nelem-offset;
   { // Only workers could have Wait roles so we know the slice must be empty
     // since we've exited the loop above.
     waitPeer<DirectRecv, DirectSend, Recv, Send, Src, Dst>(0, 0, 0, 0);
    }
    barrier(); // Has couterpart in preceding worker-only loop.
    if (Send && (flags & RolePostSend) && sliceSize > 0 && index == 0) __threadfence_system();
    __syncwarp();
   postPeer<Recv, Send>();
   offset += sliceSize;
   slice += 1;
 }
```

1. do two barriers in different branch will cause deadlock? (I haved tried and know this don't cause deadlock, but i can't find the reason clearly, I can just find some suggestions about __syncthreads(bar.sync) that don't use in branch? ) [https://stackoverflow.com/questions/12519573/cuda-syncthreads-inside-if-statements](url)
2. do the two barrier means , workers thread will arrive in the barrier(in if (tid < nworks ... )) util the no-worker threads arrive in its barrier(while (slice < SlicePerChunk) {...})?
3. what __threadfence_system really means or does. Is __threadfence_system to make the previous chunk memory operations to be done and watched by peer GPU? i found thing about memory barrier [https://en.wikipedia.org/wiki/Memory_barrier](url)
but i don't know the meaning in cuda (have seen the cuda programmiguide guide)

**Comment by jbachan** [comment]
1. Indeed we are doing something unsafe by performing `bar.sync` in different branches. Replacing with `barrier.sync` shows some perf drop. We keep our eye on this.
2. barrier() will synchronize all worker and non-worker threads together each time. Therefore both workers and non-workers must execute the same number of barrier's. Some of the worker barriers will be executed within the worker-only-if for as long as there is data to process. Then workers will proceed to the next loop to execute remaining barriers. Non-workers always skip over the worker-only-if and do all barriers from next loop.
3. threadfence_system() blocks until all previously executed stores settle in memory. We have to do this before updating the peer's step counter otherwise memory reordering could cause the peer to see the updated step count before the data actually lands, leading to corruption.
