### ISSUE TITLE
Is the result of NCCL's AllreduceSum the same for each GPUs?

### ISSUE THREAD

**Issue by ForFishes** [NVIDIA/nccl#855]
Is the result of NCCL's AllreduceSum the same for each card?

**Comment by sjeaugey** [comment]
I'm not sure which card you are referring to? If you meant GPUs, then the answer is yes.

**Comment by ForFishes** [comment]
> 

Thank you for your reply. The “card” in my question does refer to GPUs. I'm curious how the numerical stability is guaranteed under the ring-based allreducesum. As far as we know, the order of addition is different, and the result obtained is different. How does ring-allreducesum ensure that the addition order of each GPUs is the same?

**Comment by sjeaugey** [comment]
Ring allreduce may be tricky for numerical stability, because we basically perform :
```
sum over n gpus = sum over n-1 gpus + value of one gpu
```
That could cause issue when the sum becomes large and the individual value is too small to be incorporated into the total sum.

But with all that said, once the sum is complete, it will be transmitted unchanged to all GPUs. So you may suffer from ring precision with low-precision data types, but all ranks should get the same value, always.

Also note, as we scale and numerical stability becomes more of a challenge, NCCL happens to use the Tree algorithm for better performance, but also better precision.

**Comment by ForFishes** [comment]
Thank you, I understand it.

**Comment by liqing9399** [comment]
> Ring allreduce may be tricky for numerical stability, because we basically perform :
> 
> ```
> sum over n gpus = sum over n-1 gpus + value of one gpu
> ```
> 
> That could cause issue when the sum becomes large and the individual value is too small to be incorporated into the total sum.
> 
> But with all that said, once the sum is complete, it will be transmitted unchanged to all GPUs. So you may suffer from ring precision with low-precision data types, but all ranks should get the same value, always.
> 
> Also note, as we scale and numerical stability becomes more of a challenge, NCCL happens to use the Tree algorithm for better performance, but also better precision.

For the same data, if executed repeatedly, will the results of multiple allreduce operations be the same?

**Comment by sjeaugey** [comment]
>For the same data, if executed repeatedly, will the results of multiple allreduce operations be the same?

Yes I don't think any algorithm is subject to randomness.
