### ISSUE TITLE
acronym expansion?

### ISSUE THREAD

**Issue by ajschumacher** [NVIDIA/nccl#86]
Hi! Should NCCL be expanded as "NVIDIA Collective Communications Library"? Or something else? Or should NCCL not be interpreted as an initialism? Thanks!

**Comment by cliffwoolley** [comment]
"NVIDIA Collective Communication Library" is formally correct (and we do
sometimes refer to it by its full name), but you can also just call it NCCL
when referencing it, which is what we do the vast majority of the time.

Think of it like "cuBLAS", which is also technically an initialism, yet
practically nobody ever bothers to spell out "CUDA Basic Linear Algebra
Subroutines", which would be less readily recognizable than just "cuBLAS".

Thanks for inquiring!

-Cliff


On Apr 23, 2017 4:28 PM, "Aaron Schumacher" <notifications@github.com>
wrote:

Hi! Should NCCL be expanded as "NVIDIA Collective Communications Library"?
Or something else? Or should NCCL not be interpreted as an initialism?
Thanks!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/NVIDIA/nccl/issues/86>, or mute the thread

**Comment by cliffwoolley** [comment]
I guess if we really want to get pedantic, they're both acronyms, not
initialisms -- they are each pronounced as a word rather than spelled.  In
the case of NCCL, we say "Nickel".  And cuBLAS is said like "coo-blas", not
"C-U-blas".

**Comment by ajschumacher** [comment]
Thanks! I'll have to remember to say nickel! 👍

**Comment by ajschumacher** [comment]
I expanded the acronym in this: http://planspace.org/20170423-tensorflow_as_automatic_mpi/ I hope I didn't misrepresent anything! Thanks again!
