### ISSUE TITLE
Question: NCCL Tree algorithm behaviour 

### ISSUE THREAD

**Issue by mktip** [NVIDIA/nccl#919]
Greetings,

I have a question about the behavior of NCCLs Tree algorithm. I've noticed that when running the all_reduce NCCL test from the [nvidia/nccl-tests](https://github.com/NVIDIA/nccl-tests) GitHub repository and specify the NCCL_ALGO to Tree, the communication graph between the GPUs looked more like a list. I understand that this is still a valid tree, but I was wondering what influences the shape of the tree? Is it related to the topology of the GPUs being used? is there a way to make the Tree shape more pronounced and distinguishable?  or a way to explain the current shape of the tree? (as shown in the figure below, where the nodes represent the GPUs, and the arrows represent the communication taking place between them)

![NCCL-Tree-GPU-Communication](https://github.com/NVIDIA/nccl/assets/45905717/da1fde5e-0565-4a58-9891-163981cf3298)

Best regards,

**Comment by sjeaugey** [comment]
The tree is only between nodes. Within a single node, it is indeed just a chain.

**Comment by mktip** [comment]
Much Appreciated!

**Comment by liulalala** [comment]
Hi, I am wondering why within the nodes, chain structure is used rather than a tree?  Btw, between intra-node GPUs, are there also ring/tree algorithm to be chosen?

**Comment by sjeaugey** [comment]
>  why within the nodes, chain structure is used rather than a tree

That's needed to get full bandwidth. When you receive from 2 peers, you can only operate at half speed.

> between intra-node GPUs, are there also ring/tree algorithm to be chosen

Users should not have to choose. NCCL should pick the right algorithm for a given size. Each algorithm is both intra- and inter-node. There is no separation, or combination. Tree is a static combination of tree inter-node and chain intra-node (which is a form of tree but it doesn't really matter), and Ring is a set of rings that go both intra and inter-node.

For reference:
CollnetDirect is alltoall within the node and Collnet between nodes.
CollnetChain is a chain within the node and Collnet between nodes.
NVLS is NVLink SHARP within the node and Collnet between nodes.
NVLSTree is NVLink SHARP within the node and Tree between nodes.

**Comment by polarstormx** [comment]
@sjeaugey Hi,sjeaugey. I recently read the source code and discovered that a pair of double binary trees are distributed across two channels. However, this is only the way the nodes are connected. The connection method within the nodes of the two trees is the same( as you mentioned，a chain). I read the piece of paper on Two-tree algorithms given on the official website, and in my understanding, every node except root has two receiving(two childs in one tree) and two sending(two parents in both trees) peers at every time(in reduce parse, the broadcast is reversed) , so it seems that the bandwidth is fully utilized. But you say we can only use half the bandwidth, which confuses me a bit. 

Additionally, if both ring and tree can utilize the full bandwidth, and the latency of tree is better, then why in allReduce, still the selection of ring and tree is done based on the number of ranks, message size? Under what circumstances will ring perform better than tree(e.g. large/small message/nranks) ?  
Maybe the answer to both questions is the same, is there a flaw in double binary tree's algorithm?

**Comment by liulalala** [comment]
Hi sjeaugey, thank you for your nice reply! Some follow-up questions:

> When you receive from 2 peers, you can only operate at half speed.

Why there are only half speed once using a tree within a node? Do you mean (single) tree rather than double binary tree? If that is the case, then why a single tree can only get half speed?

One additional question is , regarding to the double binary tree implementation of NCCL, why there is 3 recv and 1 send at most during the reduce phase, and 3 send and 1 recv at most during the broadcast phase for non-root nodes; and 2 recv and 2 send for root nodes. Would it cause a 3:1 incast? Are there any other considerations to not schedule the transmission to make a node at most 1 recv and 1 send at each step to avoid traffic fan-in as discussed in the 2-tree paper(http://algo2.iti.kit.edu/documents/2tree.pdf)?

**Comment by sjeaugey** [comment]
> When you receive from 2 peers, you can only operate at half speed.

Sorry, that statement was confusing indeed, as it's what we do inter-node (with 2 trees x half BW = full BW).

There are many ways to do intra-node communication (ring, chain, alltoall, tree, ...). Combining intra-node and inter-node can be tricky though. The reason we chose chains within the node is because it connects easily to the inter-node trees (one chain per NIC) and works well on any topology. Also, LL/LL128 protocols have very fine-grain pipelining and low latency, so an 7-step chain is actually really, really quick to traverse the node.

Combining an inter-node tree with and intra-node binary tree could be possible indeed. But that would require us to completely rewrite the intra-node search algorithm. Currently the search looks for paths running at full speed, and we only split those "search channels" into 2 or 3 "communication channels" later on.

Now, assuming we'd write a brand new algorithm to search for multiple trees within the node, we might be able to use trees within the node as well. It's not clear how much performance we'd gain, so it could be a lot of effort for a potentially small gain. The LL128 protocol, in particular, has a long starting time but a very small per-hop latency. So it's not useful for a simple send/recv or alltoall, as there is a single step.

Regarding the 3:1 incast, we have 2:1 on the network through the PCI lanes and 1 from NVLink. The 1 from NVLink doesn't count in BW calculations as it's not taking BW from the PCI/Network side. On non-NVLink systems though, we do not use Trees for large sizes, only for small sizes.

**Comment by liulalala** [comment]
Thank you sjeaugey. I got that intra-node tree may not bring much performance gain since the GPUs in intra-node is quite small scale (e.g., 8) and setting up too much LL128 channels between different GPUs is costly.

But I still got much confused that,

(i) why a single tree can only get half BW? Why can not the nodes connected through a tree-edge get the full bandwidth? 
(ii) 

> we have 2:1 on the network through the PCI lanes and 1 from NVLink. The 1 from NVLink doesn't count in BW calculations as it's not taking BW from the PCI/Network side.

According to the code that create primitives to set up connections in a tree (src/collectives/device/all_reduce.h/runTreeSplit), it uses struct FanAsymmetric to set up multiple connections to different children of a node. Do you mean that one of those connections (e.g., to a certain child/parent) is through PCI lanes and another one (e.g., to another child/parent) through NVLink? But I thought that different nodes are connected through PCIe or IB, and intra-node GPUs are connected through NVLinks previously. 

Besides, no matter by what means that the nodes are connected, if the arriving data rate exceceeds the link rate of the receiving node, it may overwhelm the receiving buffer of the node? Please point out if my understanding is wrong.

**Comment by polarstormx** [comment]
@sjeaugey Thanks a lot for your answer! Now I understand why we use chain intra-node. 
However, I am still not quite sure:
(1) Can the tree algorithm fully utilize bandwidth like the ring algorithm? If not, why?
(2) Is the latency performance of the tree algorithm always better than ring algorithm(logn vs n)?

If the answer to both of these questions is yes, then it seems that the tree algorithm would be chosen for all allReduce scenarios. But in tuning.cc, I still see calculations for latency and bandwidth, so in which scenarios would the tree algorithm perform worse?

You mentioned that on non-NVLink systems, we do not use Trees for large sizes, only for small sizes. Is this due to the incast mentioned earlier? So on systems with NVLink, the tree algorithm is always used?
Please correct me if I have any misunderstandings.
