### ISSUE TITLE
Tree bandwidth larger than ring on two nodes

### ISSUE THREAD

**Issue by dearsxx0918** [NVIDIA/nccl#946]
Hi,
    I used NCCL latest code to test A100 * 2 nodes. Seems tree algorithm much better than ring on this topology. But to my understanding, ring always better when the data size large enough.
    Could you please help me on this?
Best regards,
-Edda

**Comment by sjeaugey** [comment]
2 nodes is a special case. With Tree, on 2 nodes, traffic is not uniformly balanced and we have 2x less traffic on the network than on the intra-node connections (NVLink for example). If the bottleneck is the network and intra-node bandwidth is far from being saturated, the Tree performance can go up to ~2x the network speed.

Because of that, on many platforms, NCCL should use Tree on 2 nodes for large sizes.

**Comment by dearsxx0918** [comment]
Thanks for your quick reply!
