### ISSUE TITLE
Why not create a new API for allToAll on NVSwitch3 based NCCL?

### ISSUE THREAD

**Issue by dearsxx0918** [NVIDIA/nccl#951]
Hi sjeaugey，
    Seems nvswitch3' multicast can support more efficient alltoall than grouped send/recv. Is there any possibility to develop a new API that supprot alltoall when NVswitch3 found?
Best regards,
-Edda

**Comment by sjeaugey** [comment]
I'm not sure we need a new API to use NVLink SHARP inside an alltoall. We could detect that the group of send/receive is  sending to all GPUs inside the node, and therefore use NVLink SHARP to address that group of GPUs. Which would also cover scatter operations, not only alltoall. Keeping a send/receive API has that advantage that everything we do applies to all uses cases. It has some drawbacks as well, so maybe one day we'll add more APIs, but as much as possible, we try to apply optimizations to send/receive, so that it benefits as many use cases as possible.

Now since NVLink SHARP would also copy data to the local GPU, using it would incur more traffic hence would be slower than direct send/receive. It could help in reducing the number of SMs however, since it offloads part of the copies to the switch. So maybe we'll consider that if compute/alltoall overlap is something that becomes important.

**Comment by BiduCui** [comment]
<img width="784" alt="image" src="https://github.com/NVIDIA/nccl/assets/133873636/9c7dda17-3faa-4398-8c1f-9cd8d8e0dc34">
@sjeaugey， Based on the schematic diagram of NVLink Sharp, it seems that NVLink Sharp has fewer traffic counts compared to send-recv, which appears somewhat contrary to your expressed understanding. How should this be interpreted?

**Comment by sjeaugey** [comment]
The drawing is incorrect. The text is correct however: 1 write is amplified to N writes, which should point to all 4 GPUs including the initiator.

**Comment by dearsxx0918** [comment]
Thanks for you reply!
