### ISSUE TITLE
cannot open shared object file

### ISSUE THREAD

**Issue by duduRodrigues** [NVIDIA/nccl#96]
I'm trying to run caffe with nccl and it build successfully. But when i try to run my application i keep getting this error: "error while loading shared libraries: libnccl.so.1: cannot open shared object file: No such file or directory" and i think that this is something related to be or not to be the "-dev" version. Can someone help me? Thank you!

**Comment by sjeaugey** [comment]
If installing from debs, you should always install libnccl1_<version>.deb.

If you need to compile with NCCL (which seems to be your case) you will also need libnccl-dev_<version>.deb but I guess you already have it since the build worked.

**Comment by duduRodrigues** [comment]
I've installed the NCCL using exactly these commands:
$ git clone https://github.com/NVIDIA/nccl.git
$ cd nccl
$ sudo make install -j4 - See more at: http://www.nvidia.com/object/caffe-installation.html#sthash.dtwPCMBq.dpuf

Did i've done it right? I found this tutorial at http://www.nvidia.com/object/caffe-installation.html teaching how to install NCCL and caffe together, but i do not know if it compiles the -dev version.

**Comment by sjeaugey** [comment]
Oh, OK, so you built it from source.
make install will install everything in ${PREFIX}/include and ${PREFIX}/lib. By default PREFIX is /usr/local.

So /usr/local/include may be in your default include path, which is why you managed to compile Caffe, but /usr/local/lib may not be in your default library path. On my ubuntu 16.04 install, I have a /etc/ld.co.conf.d/libc.conf file with the line "/usr/local/lib", but that may vary between distributions. You may want to create that file then run "ldconfig" as root to take that change into account.

Alternatively, as a quick-and-dirty solution, you may want to "export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH".

**Comment by duduRodrigues** [comment]
It finally worked. The quick-and-dirty solution worked really fast :P Thank you, man!!! When i have a little more time i will try to do the right thing.

**Comment by Light--** [comment]
i was testing theano with pygpu backend. install nccl soved my errors of ```
GpuArrayException: Could not load "libnccl.so": libnccl.so: cannot open shared object file: No such file or directory
 ```

https://developer.nvidia.com/nccl
