### ISSUE TITLE
Some questions about proxy and kernel in nccl

### ISSUE THREAD

**Issue by ziannchen** [NVIDIA/nccl#966]
What is the interaction between kernel and proxy thread？

**Comment by sjeaugey** [comment]
Proxy threads act as relay so that GPUs can send data to a remote peer.

Between the proxy thread and the CUDA kernel, there is a FIFO with head/tail and a circular buffer, just like between GPUs when communicating intra-node. Therefore, the GPU sends data to a FIFO and the proxy forwards that data to the next GPU's receiving FIFO.

**Comment by ziannchen** [comment]
When proxy want to send data to network, how does it know the data is ready, and when data is not ready what does proxy thread do? How does they notify each other?

**Comment by sjeaugey** [comment]
The `head`/`tail` counters indicate what data in the FIFO is ready to receive. When there is nothing to receive, the proxy just polls the memory. When all operations are complete, the proxy thread sleeps and is woken up when we start new NCCL operations.

**Comment by ziannchen** [comment]
Well, but I still have some questions.

**Comment by sjeaugey** [comment]
1. Yes. head/tail counters are there for that purpose and they're supposed to be used with proper memory fencing.
2. The proxy thread has an internal scheduler, and progresses all networking operations for all channels in a round-robin manner. RDMA operations don't need much CPU work; a single CPU can handle all channels.

**Comment by sjeaugey** [comment]
The GPU is calling __threadfence_system(), which should guarantee the memory ordering is correct.
For the CPU it's a complicated subject and there are many techniques to guarantee the memory is correct when the GPU sees it, and how we do it depends on the platform and GPU constraints. We just take care of doing it correctly so that users don't have to figure it out.

**Comment by shanleo1986** [comment]
@ziannchen Hi, I have aslo some questions about the proxy thread, can we contact with each other and learn together?
If it is possible, please contact me via my e-mail: shanleo1986@163.com
Thank you, and wish to receive your response.

**Comment by MaoZiming** [comment]
@sjeaugey Hi, could you kindly give some code pointers on where the FIFO is implemented, and especially on how the changes made by the CPU to the FIFO queue is visible to the GPU? Thank you!

**Comment by sjeaugey** [comment]
Here are the structs with the head/tail counters we allocate from the host:
https://github.com/NVIDIA/nccl/blob/master/src/include/comm.h#L42-L66

Then we set pointers within that struct so that the device code can use it:
https://github.com/NVIDIA/nccl/blob/master/src/include/device.h#L129-L147
