### ISSUE TITLE
How to use multiple HCA?

### ISSUE THREAD

**Issue by asdfry** [NVIDIA/nccl#981]
nccl version: 2.18.3+cuda12.0

Hi, I'm new to using nccl and rdma.

I have two servers as below.
|server|gpu|hca|
|---|---|------|
|master|A100 * 2|mlx5_2(ib), mlx5_3(ib), mlx5_bond_0(eth)|
|worker|T4 * 2|mlx5_0(ib), mlx5_1(ib), mlx5_bond_0(eth)|

I want to **use all infiniband adapters** when multinode training.
So I set env and run the code and monitored each hca with perfquery, but **nccl uses only one HCA**.

Here is env that I set. (I touched envs that seems to be related with rdma by my standards)
NCCL_DEBUG=INFO
NCCL_DEBUG_FILE=nccl-debug.%h.log
NCCL_TOPO_DUMP_FILE=nccl-topo.xml
NCCL_MIN_NCHANNELS=4
NCCL_IB_QPS_PER_CONNECTION=4
NCCL_IB_HCA=mlx5_0,mlx5_1,mlx5_2,mlx5_3

I run code with huggingface accelerate + deepspeed.
1. `source $HPCX_HOME/hpcx-init.sh && hpcx_load`
2. `accelerate launch train.py`

![multinode_training](https://github.com/NVIDIA/nccl/assets/39879672/831bfeaf-663a-47d1-9f80-cfaa660ab022)

nccl log files
[nccl-debug.master.log](https://github.com/NVIDIA/nccl/files/12497450/nccl-debug.master.log)
[nccl-debug.worker.log](https://github.com/NVIDIA/nccl/files/12497470/nccl-debug.worker.log)

master's topology
```
<system version="1">
  <cpu numaid="0" affinity="0000ffff,0000ffff" arch="x86_64" vendor="GenuineIntel" familyid="6" modelid="106">
    <pci busid="0000:31:00.0" class="0x030200" vendor="0x10de" device="0x20f1" subsystem_vendor="0x10de" subsystem_device="0x145f" link_speed="16.0 GT/s PCIe" link_width="16">
      <gpu dev="0" sm="80" rank="0" gdr="1"/>
    </pci>
    <pci busid="0000:17:00.0" class="0x020700" vendor="0x15b3" device="0x101b" subsystem_vendor="0x15b3" subsystem_device="0x0008" link_speed="16.0 GT/s PCIe" link_width="16">
      <nic>
        <net name="mlx5_2" dev="0" speed="100000" port="1" guid="0x2078d70003fd7010" maxconn="1" gdr="1" coll="1" latency="0.000000"/>
        <net name="mlx5_3" dev="1" speed="100000" port="2" guid="0x2078d70003fd7010" maxconn="1" gdr="1" coll="1" latency="0.000000"/>
      </nic>
    </pci>
  </cpu>
  <cpu numaid="1" affinity="ffff0000,ffff0000" arch="x86_64" vendor="GenuineIntel" familyid="6" modelid="106">
    <pci busid="0000:ca:00.0" class="0x030200" vendor="0x10de" device="0x20f1" subsystem_vendor="0x10de" subsystem_device="0x145f" link_speed="16.0 GT/s PCIe" link_width="16">
      <gpu dev="1" sm="80" rank="1" gdr="1"/>
    </pci>
  </cpu>
</system>
```

nvidia-smi topo -m (master)
```
        GPU0    GPU1    NIC0    NIC1    NIC2    CPU Affinity    NUMA Affinity
GPU0     X      SYS     NODE    NODE    NODE    0-15,32-47      0
GPU1    SYS      X      SYS     SYS     SYS     16-31,48-63     1
NIC0    NODE    SYS      X      PIX     NODE
NIC1    NODE    SYS     PIX      X      NODE
NIC2    NODE    SYS     NODE    NODE     X 

NIC Legend:

  NIC0: mlx5_2
  NIC1: mlx5_3
  NIC2: mlx5_bond_0
```

nvidia-smi topo -m (worker)
```
        GPU0    GPU1    NIC0    NIC1    NIC2    CPU Affinity    NUMA Affinity
GPU0     X      SYS     NODE    NODE    SYS     0-15,32-47      0
GPU1    SYS      X      SYS     SYS     NODE    16-31,48-63     1
NIC0    NODE    SYS      X      PIX     SYS
NIC1    NODE    SYS     PIX      X      SYS
NIC2    SYS     NODE    SYS     SYS      X 

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1
  NIC2: mlx5_bond_0
```

It's my first time registering an issue, so the content may be very poor.
Please help me...

**Comment by sjeaugey** [comment]
NCCL probably found that using 2 ports would not improve performance because there are other bottlenecks in the system, hence you would not get 24 GB/s but only <=12 GB/s anyway.

You could force NCCL to use both ports by modifying the topology to return `50000` as the port speed and then re-injecting it with `NCCL_TOPO_FILE=system-50gbps.xml` but you'd need to have a different topo file per node (e.g. write a different topo file in `/etc/nccl/topo-50gbps.xml` and write `NCCL_TOPO_FILE=/etc/nccl/topo-50gbps.xml` in `/etc/nccl.conf`).

I'd advise to run the NCCL perf tests, see what performance you are getting, then try the trick above, run again, and see if you could get better performance. Using 2 NICs instead of 1 will also use 4 SMs instead of 2, meaning there will be less compute resources available for other parts of the training. That's the reason why NCCL keeps the number of NICs used to a minimum as it also conditions GPU SM usage.

**Comment by asdfry** [comment]
Thanks very much for kindly reply!
